### ISSUE TITLE
replayable test generation

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1198]
- Executable which creates a testnet, creates accounts, mines blocks, and performs transactions for a set amount of time
- Logs actions to a file
- Tests consist of playing back the log file using the application and ensuring that results are as expected.

w.r.t. to mining blocks:
When generating, it makes sense to actually mine them on the testnet.
To keep results consistent when replaying, the runner would pretend to be a miner but just return the pre-mined blocks.

**Comment by gavofyork** [comment]
probably some overlap with the geth team's hive project.

**Comment by debris** [comment]
cc @tomusdrw

**Comment by tomusdrw** [comment]
https://github.com/tomusdrw/hive

**Comment by 5chdn** [comment]
This _tests_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _nice to have_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by lght** [comment]
I'm currently working on something related, and spent yesterday trying to help someone get a reliable smart contract test environment. 

I like the hive tool, but would also really love to have a native testnet. 
This is partly selfish, since it would be a first step to being able to deploy cargo-fuzz onto the testnet.

How nicely does hive play with some of Go's fuzzing frameworks? 
Wouldn't want to duplicate work if hive can do most/all of what I want.

**Comment by debris** [comment]
I'm closing it, cause right now we do not have any plans to implement this
