### ISSUE TITLE
Address errors should be more fine-grained

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2152]
The supplied address is an invalid network address should be augmented with: the supplied address has no checksum formatting & the supplied address has failed the checksum formatting (validation, Ken)

(Split from https://github.com/ethcore/parity/issues/2120)

**Comment by jacogr** [comment]
As per https://github.com/ethcore/parity/issues/3500

should be obviously green when address checksum works out or is in the addressbook. should be yellow if there is no checksum (all lowercase). should be red if checksum doesn't work out.

**Comment by 5chdn** [comment]
This issue is labeled with _security_: The client fails to follow expected, security-sensitive, behavior. It is however, neither assigned to a developer nor attached to milestone. It's also inactive for more than 6 months.

I'm tempted to close this issue as _wontfix_ unless someone objects, and adds an assignee and milestone within 7 days,

**Comment by debris** [comment]
I'm closing it as the issue seems to be inactive. Please reopen it in `parity-ui` repo if it's still relevant
