### ISSUE TITLE
Expose a list of whitelisted accounts per dapp

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2285]
After #3382.

We want to prevent random untrusted dapps from accessing a user's list of accounts. Dapps should each see only the list of accounts that the user desires them to see, rather than all of them as at present. Signer snippet UI should support editing this list, possible while using the Dapp.

- [ ] Signer should allow user to configure which dapps can see which accounts;
- [x] RPC should only report accounts that the dapp is allowed to see.

(Split from https://github.com/ethcore/parity/issues/2118)

**Comment by jacogr** [comment]
From @gavofyork 

```
Dapps should each see only the list of accounts that the user desires them to see, rather than all of them as at present. Signer snippet UI should support editing this list, possible while using the Dapp.
```

**Comment by gavofyork** [comment]
@jacogr / @tomusdrw how is this one doing?

**Comment by jacogr** [comment]
Default whitelist UI basically done, we have one small issue left on Parity that breaks things somewhat upon first set. (However being addressed). 

First round however is only for the global/default whitelist, not specific per dapp.

**Comment by gavofyork** [comment]
postponing to 1.6 then

**Comment by tomusdrw** [comment]
Note: signer bar needs to know on which dapp it's being displayed:
1. In chrome extension it's an iframe INSIDE the dapp
2. When running builtins/network/local it's OUTSIDE of the dapp, which is run in iframe.

Need to work correctly for both cases.

**Comment by tomusdrw** [comment]
Related #4580

**Comment by 5chdn** [comment]
This issue is labelled with _security_: The client fails to follow expected, security-sensitive, behaviour; and _asap_: No need to stop dead in your tracks, but the issue should be addressed as soon as possible. It is assigned to @jacogr and @tomusdrw and attached to milestone 1.7. It is inactive for 3 months.

Could you comment within 7 days on the progress of this issue and if this is still relevant for 1.7? Or close this issue if a fix is available.

**Comment by tomusdrw** [comment]
RPCs for dapp-specific accounts are complete. UI should work fine for Parity Extension Signer, but doesn't work correctly for network/builtin dapps.

**Comment by lght** [comment]
When making changes to the dapp's account whitelist, should we require the user to re-enter their account password?

Thinking about ways to implement levels of security, so that someone with local/rpc access can't arbitrarily change the account list. So, if an attacker has rpc access, and the account owner has unlocked the account owning the dapp whitelist, what currently prevents such an attacker from editing that list?

**Comment by tomusdrw** [comment]
This set of APIs is only available on Secure WebSocket connection by default. Such connection requires additional access token to be present while connecting to WS server.

**Comment by tomusdrw** [comment]
@jacogr do we still want this to be maintained by the node? I think that currently with the standalone Parity UI the dapps might not be distinguishable for the node, right?

**Comment by 5chdn** [comment]
Yes, please move this to the Parity UI repository.
