### ISSUE TITLE
Autogenerated JS API

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#2646]
- [ ] Autogenerate JSON RPC introspection functions for each JSONRPC module;
- [ ] parity.js should generate JS API from the introspection functions.

**Comment by rphmeier** [comment]
@jacogr and I spoke about this a bit -- I think this would take quite a bit of macro magic, and the immediate plans I see seem a bit fragile. It might just be better to have the core/js folks create joint PRs for any RPC-related changes, incorporating the changes to both sides of things.

**Comment by maciejhirsz** [comment]
Related to #1905:

Instead of going macro heavy and/or parsing rust syntax to AST (which would be particularly useful to extract field comments for serde-enabled structs used in RPC), an easy win would be to _only_ parse the traits. This can be done quite easily with regex, although it's much more limited in scope.

If going all the way from Rust to parity.js interfaces and documentation isn't feasible on it's own, a tool to synchronize parity.js with Rust codebase would already go a long way to reduce the maintenance cost of having to maintain two lists of all RPC methods.

For reference, requoting myself from Slack:
> I’m slowly driving the RPC docs to completion here (`parity_*` and `trace` modules are left, out of which only `parity_set` is most lacking and I’ll cover it first), and while I’m pretty happy with how the markdown autogen is working, I also fear it’s not very future proof. The main issue I see is that keeping the .js interface files in sync with traits from Rust codebase is a pretty high maintenance cost.
> I’ll try to pen a proposal for the trait documentation later today, trying to keep it somewhat familiar with javadoc/jsdoc format for parameter description in rust doc comments (`/// @param name description`) while deriving most of what I can from types themselves.
> Ideally a json file for the UI could be generated from the traits too, so we can have Single Source of Truth™ for RPC.

**Comment by gavofyork** [comment]
one for the long-term bin.
