### ISSUE TITLE
RPC port bind error shouldn't be possible

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#2813]
If RPC address is already in use, you currently get this:

```
2016-10-22 16:13:51  Error starting network: StdIo(Error { repr: Os { code: 48, message: "Address already in use" } })
RPC io error: Address already in use (os error 48)
```

It should dynamically create new RPC addresses to allow for multiple `parity`s running.

**Comment by tomusdrw** [comment]
Duplicate of #2164

**Comment by tomusdrw** [comment]
Oops, sorry just noticed that you proposed binding to different port as a solution.

**Comment by gavofyork** [comment]
moving to 1.5 since IPC will be disabled for 1.4

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year and not assigned.

@paritytech/core-devs Please, add an assignee within 7 days and review the _1.9 and beyond deadline_ or close it otherwise. Thanks.
