### ISSUE TITLE
Prepare debian package for parity

### ISSUE THREAD

**Issue by debris** [paritytech/parity#286]

**Comment by nyetwurk** [comment]
I don't see any debian packages there

**Comment by nyetwurk** [comment]
These are completely useless:

http://ppa.launchpad.net/ethcore/ethcore/ubuntu/dists/

**Comment by debris** [comment]
cc @paritytech/ci

**Comment by joshua-mir** [comment]
@nyetwurk we haven't had distro-specific packages since depreciating our user-facing wallet - https://github.com/paritytech/parity-ethereum/issues/8649

The current distribution options are snap, docker, and our binaries (ideally via the manual update script - certain distros have community-maintained packages and repos but none are provided directly by Parity.
