### ISSUE TITLE
Edit Metadata, default button should be save

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3141]
Applies to:
- accounts
- contracts
- addressbook

To reproduce:
- edit your tags
- hit TAB

![screen shot 2016-11-03 at 16 00 35](https://cloud.githubusercontent.com/assets/738724/19971229/b741d8fc-a1de-11e6-84ba-7dc396b9bcdf.png)

At that point, you may even have already hit ENTER :)
If you did so, you just cancelled the change you intended to make because the CANCEL button is the 'next' control after the tab field.

Editing the metadata is never very critical so I don´t see any safety issue setting SAVE as default.

**Comment by 5chdn** [comment]
Actually, CANCEL is not the default but the next selected field after you use the TAB key. Do you propose to change the order of the interface items?

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
