### ISSUE TITLE
Simplify parity_checkRequest & eth_getTransactionReceipt boilerplate

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3333]
```
contract.instance.someFunction
  .postTransaction({}, [])
  .then((signerRequestId) => {
    api.pollMethod('parity_checkRequest', signerRequestId);
  })
  .then((txHash) => {
    api.pollMethod('eth_getTransactionReceipt', txHash);
  })
  .then((txReceipt) => {
    ...
  });
```

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/core-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by folsen** [comment]
Closing, if there's any specific proposal on how it can be simplified please reopen.
