### ISSUE TITLE
Use Atom editor for contract editor

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3409]
Would provide a better editing experience

**Comment by jacogr** [comment]
The editor used Ace was the original editor that was (a) included on GitHub , (b) provided the basis for the first Atom experiments - it has grown since then. (Ace is maintained by cloud9 & Mozilla - https://en.wikipedia.org/wiki/Ace_(editor)#Projects_using_Ace)

Not sure this would be such a simple task as it stands - we don't want to write/provide our own React bindings (available for Ace). In addition, I know that the Atom team didn't plan to support embedding in the web some time ago, it may have changed since then. (Since Atom is Node based the environments are quite different)

Agreed with "nice to have", at this point I would rather see what basics are missing from the initial implementation and can be done with minimal effort (UX wise, we have some nigglies)

**Comment by ngotchac** [comment]
see https://github.com/facebooknuclide/atom-in-orbit
