### ISSUE TITLE
Decentralized applications tab blank when using --dapps-user/--dapps-pass

### ISSUE THREAD

**Issue by woftor** [paritytech/parity#3413]
When using a username / password to start parity like this:

`parity --dapps-user gekkehenkie --dapps-pass secret`

The decentralized applications tab is blank when clicking on it. Without username/password all is well. Tested with 1.4.2 beta (latest from git).

Probably related to: https://github.com/ethcore/parity/issues/3412 , but not sure.

**Comment by tomusdrw** [comment]
With new UI authorization feature doesn't serve it's purpose anymore. 
Options:
1. Ask for credentials for :8080 (a tiny iframe?)
2. Protect signer interface with user/password also

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/ui-devs Dapps server authentication has been removed. Can this ticket be closed?

**Comment by ngotchac** [comment]
Yes, this is no longer relevant. Please re-open if I'm wrong @tomusdrw

**Comment by tomusdrw** [comment]
Correct, dapps can be retrieved via RPC now as well.
