### ISSUE TITLE
Tag build should ignore `[ci skip]`

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#3484]
Tag build should ignore `[ci skip]` and start regardless.

**Comment by General-Beck** [comment]
[ci skip] - first line in comment or body

**Comment by 5chdn** [comment]
This issue is labelled with _asap_: No need to stop dead in your tracks, however issue/PR should be addressed as soon as possible. But it is inactive for more than 6 month and neither assigned nor linked to a milestone.

@paritytech/ci Please, review this ticket within 7 days, assign it to someone at devops and decide on a deadline.

**Comment by jesuscript** [comment]
this requires a tricky solution, should be discussed

**Comment by folsen** [comment]
Closing, @5chdn if this is something you want for builds/releases in general, please re-open in devops repo.

**Comment by 5chdn** [comment]
Moved https://github.com/paritytech/devops/issues/102
