### ISSUE TITLE
Useful accounts should float to top of list

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3562]
Accounts that hold ether should float to the top of the account list. Accounts holding _something_ should be next. Empty accounts should be at the bottom.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year and not assigned yet.

@paritytech/ui-devs Please, review within 7 days the 1.8 deadline and add an assignee or close it otherwise. Thanks.
