### ISSUE TITLE
GHH to display list of old transactions

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3648]
- No events, but can pull list of transactions and decode
- make links clickable (both content & original)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/dapp-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.
