### ISSUE TITLE
Safari displays a border around the transfer dropdown

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3679]
![safari-parity 2016-11-29 17-32-51](https://cloud.githubusercontent.com/assets/1424473/20719272/aa4c6ea0-b65b-11e6-9509-3afbfb9edcd0.png)

**Comment by derhuerst** [comment]
Interesting, I cannot confirm this. Safari `10.0.1`.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by ngotchac** [comment]
@jacogr Is this still an issue ? Don't have Mac OS, cannot test...
