### ISSUE TITLE
TRACE module not working with PENDING tag 

### ISSUE THREAD

**Issue by diego-G** [paritytech/parity#3837]
I'm not able to get pending transactions with the Parity modules trace_filter or trace_transaction.
I have  `--tracing=on` activated. 

It works when using trace_filter to get the internal transactions related to a contract. But no when I try to get pending blocks.

Same for trace_transaction. If I quickly use a tx hash that is pending, It returns empty response.

I use `{fromBlock : "pending" , toBlock: "pending" ... }`

@tomusdrw said: "I'm afraid that trace_* API is not available for pending state"

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/core-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.
