### ISSUE TITLE
Rename all occurences of `Signer` in user facing messages

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#3855]
Since the CLI options are now called `--ui` it should not mention signer at all.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

Also, while I think this is already complete in most cases, we should also consider not using the term _UI_ (technical term) but _Wallet_ (the product).

@paritytech/ui-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by 5chdn** [comment]
Does this affect these commands too?

    parity signer new-token [options]
    parity signer list [options]
    parity signer sign [ <id> ] [ --password FILE ] [options]
    parity signer reject <id> [options]

Can't find many _Signer_ references at all.

**Comment by tomusdrw** [comment]
I think this can be safely closed now. AFAICT all instances of Signer in the core client and UI are justified.
