### ISSUE TITLE
Release sources missing identifying git-information resulting in UNKNOWN identifiers

### ISSUE THREAD

**Issue by SjonHortensius** [paritytech/parity#3889]
I noticed that when packaged, some parity releases don't contain a proper identifying version. This is the case when using a distro (such as [Archlinux](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/parity)) that compiles parity from source, instead of distributing the precompiled binaries.

This is caused by the release`.zip` not containing any identifying information for the vergen crate that was introduced in https://github.com/ethcore/parity/commit/ea187253a23d7394720d3b071d5888d30f2227d0.

This results in nodes that identify themselves as `Parity/v1.4.6-beta-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.13.0`. There are currently 21 of such nodes listed (search for `unknown` in the **right** search-box [on ethernodes.org](http://ethernodes.org/network/1/nodes).

This could be fixed by patching `util/src/misc.rs` when releasing; or adding a correct `out/version.rs`. Since I am unfamiliar with the release-process I am unsure which (if any) of these would be preferred.

---

Completely unrelated; I noticed the 1.4.6 release sources contain compiled 1.4.0 debian packages; I'm not sure if this is intentional but it seems incorrect.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

It's probably sufficient to patch out any 'unknown' commit strings to mark major and minor releases with something like this `Parity/v1.4.6-beta/x86_64-linux-gnu/rustc1.13.0`. The commit of a tagged release usually always stays the same.

@paritytech/core-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by 5chdn** [comment]
Interestingly, builds from git-tags also get an _unstable_ string:

**Comment by arkpar** [comment]
`cargo build --features final` to get rid of `unstable` in the version

**Comment by 5chdn** [comment]
> cargo build --features final to get rid of unstable in the version

@tensor5 ^ fyi & thanks.

**Comment by tensor5** [comment]
Thanks @5chdn and @arkpar. BTW, does anybody knows why the git commit string in `Parity/v1.6.8-beta-c39622952-20170608/x86_64-linux-gnu/rustc1.17.0` ends up being 9 characters long? Shouldn't it be 7?

**Comment by arkpar** [comment]
We chose 9 out of 40 to reduce chance of collision.

**Comment by arkpar** [comment]
`UNKNOWN` has been removed from the version string
