### ISSUE TITLE
registry should show reverse to be confirmed

### ISSUE THREAD

**Issue by derhuerst** [paritytech/parity#4079]
it should show those who have been `ReverseProposed` before by someone.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since January, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
