### ISSUE TITLE
Cater for non-ETH chain currency symbols

### ISSUE THREAD

**Issue by cseberino** [paritytech/parity#4123]
When submitting contracts and other things that require payments, Parity labels
currency as ETH even when should be ETC.

Possible to somehow add a conditional instruction in code to adjust when "--chain classic"
switch used?

**Comment by jacogr** [comment]
Affects -

1. Dapps
2. UI naming
3. UI icons

(Non-shared code for ETH naming, also for private chains?)

**Comment by cseberino** [comment]
Do whatever you want for private chains.  Getting the web UI right is vital
however.



_______________________________________

Christian Seberino, Ph.D.
Phone: (936) 828-8747
Email: cseberino@gmail.com
_______________________________________

**Comment by cseberino** [comment]
ETC currency is always officially called ETC so this is definitely a bug rather than just
an annoyance.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since January, neither assigned nor linked to any milestone.

@paritytech/ui-devs @paritytech/dapp-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by keorn** [comment]
Either based on a contract lookup or a chain spec file.

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/77
