### ISSUE TITLE
Warning messages in contract development squashed

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4185]
![parity 2017-01-17 09-07-53](https://cloud.githubusercontent.com/assets/1424473/22012484/87746874-dc94-11e6-9de1-659c002eb598.png)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since January, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.
