### ISSUE TITLE
Transactions with `min_block` should be cancellable/editable

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4229]
Transaction Queue Viewer should treat those transaction in a special way.

Might be good to also update UI to change the message from "waiting for confirmations" to "waiting for block" first

**Comment by 3esmit** [comment]
Also, would be nice to have a "cancel" option and don't lose them at parity restart.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since January and not assigned yet.

@paritytech/ui-devs Please, review the 1.8 deadline within 7 days and add an assignee or close it otherwise. Thanks.

**Comment by ngotchac** [comment]
This feature is now available in the Wallet :)
