### ISSUE TITLE
Dapps server should return ContentSecurityPolicy headers

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4315]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by 5chdn** [comment]
This issue is labelled with _security_: The client fails to follow expected, security-sensitive, behavior. It is inactive for 4 months and not assigned to any developer. It is however, scheduled for the 1.7 release.

Please, comment within 7 days if this deadline is realistic, and assign a developer to the task or close the ticket if the issue is fixed or stale.

**Comment by tomusdrw** [comment]
It's still relevant, but not critical. Can be addressed after #5580 is merged.
