### ISSUE TITLE
Make AccountCard display consistent height

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4373]
As mentioned in https://github.com/ethcore/parity/pull/4355

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since January, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
