### ISSUE TITLE
High CPU usage generated by hyper after closing connection without response

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4389]
To reproduce:
```
curl --data '{"method":"eth_sendTransaction","params":[{"from":"0xb60e8dd61c5d32be8058bb8eb970870f07233155","to":"0xd4e8dd67c5d32be8058bb8eb970870f072445675","gas":"0x76c0","gasPrice":"0x9184e72a000","value":"0x9184e72a","data":"0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
This will trigger a popup in GUI, but instead of confirming it just `CTRL+C` curl awaiting the answer. It causes `hyper` to consume 100% of single core.

**Comment by tomusdrw** [comment]
Re-opening, since the fix was reverted.

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and was fixed 3 months ago but the fix was reverted. It's assigned to @tomusdrw and linked to the _patch_ milestone.

Could I get an update within 7 days if this is fixed or not and if you are going to re-introduce the fix?

**Comment by ocminer** [comment]
I can confirm this issue as well, is there a fix in sight ?

**Comment by tomusdrw** [comment]
#5580 should contain a fix.
