### ISSUE TITLE
When developing contract "Deploy" should actually mean "Compile and Deploy"

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4394]
Currently you can by accident deploy old version of contract if you don't compile it manualy before deployment (also Auto-compile checkbox doesn't seem to be working)

Proposals:
1. Deactivate "Compile" if contract was not altered after last compilation
2. Deactivate "Deploy" if contract was altered after compilation, or modify the behaviour to "Compile & Deploy"

Current behaviour on screenshot:
Code is not valid, Deploy is active and will deploy previous version, no error messages displayed despite "Auto-compile" being checked.
![screenshot from 2017-02-02 09-26-37](https://cloud.githubusercontent.com/assets/581548/22541939/b9487f7e-e929-11e6-88ac-0c46143c4ef9.png)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since February, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
