### ISSUE TITLE
Duration limit required even if Homestead transition is zero

### ISSUE THREAD

**Issue by lgpawel** [paritytech/parity#4401]
Minor annoyance: if using a chain spec with `homesteadTransition` at 0, `durationLimit` should not be required, as the Homestead difficulty evolution does not use this parameter at all. Yet in such cases Parity quits with `Spec json is invalid`. (I presume this may be fixed easily by just letting the `durationLimit` to default to, say, `0xd` whenever it's not present, regardless of the `homesteadTransition` value.)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since February, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment]
Yes, sorry for the noise.
