### ISSUE TITLE
Cannot specify Decimals Places of Smallest Unit when watching contract for ERC20 token

### ISSUE THREAD

**Issue by JanKalin** [paritytech/parity#4511]
For example, watching DGD at address `0xE0B7927c4aF23765Cb51314A0E0521A9645F0E2A`.
Tokens are displayed as integers without the possibility of diving the amount by 10^9.

E.g., the address `0xA25784714A35da4AB9f50922eD535E0F5935FAA2` contains 0.195 DGD, which is displayed as 195,018,212 DGD. Bafflingly, when one slides the toggle to the right, 0.000000000195018212 ETH are displayed.

![image](https://cloud.githubusercontent.com/assets/18305372/22834435/63e09f34-efb5-11e6-9a69-6bc3f687abc9.png)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since February, neither assigned nor linked to any milestone.

Also, the toggle should use the token TLA instead of ETH in this case, related to #4123.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
