### ISSUE TITLE
Replace parity_postTransaction usages

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4575]
Either `parity_postSignTransaction` or `parity_broadcastTransaction` to be used

**Comment by rphmeier** [comment]
I think we should deprecate/remove this RPC after this is done as well.

**Comment by tomusdrw** [comment]
Requires modifications in core as well:
`parity_postTransaction` should be renamed to `parity_postSignTransaction`
`parity_checkRequest` should return signed RLP instead of hash.

`eth_sendTransaction` should print warnings that `eth_signTransaction/parity_postSignTransaction + eth_submitTransaction` should be used instead.

**Comment by vieiralc** [comment]
@tomusdrw How can I make these changes?

**Comment by Tbaut** [comment]
@vieiralc these changes should be made in the code, not by the end user.

**Comment by vieiralc** [comment]
@Tbaut Ok, so I'll try to update parity as you said, thanks

**Comment by folsen** [comment]
@jacogr @tomusdrw How high priority is this? I don't understand the motivation behind it. Is it possibly an issue we want to put a bounty on for external contribution?

**Comment by tomusdrw** [comment]
IMHO can be closed, I don't remember the motivation behind it. I think the idea was to separate signing and broadcasting.
