### ISSUE TITLE
Simple peer finding problems

### ISSUE THREAD

**Issue by slothbag** [paritytech/parity#4680]
I have set up two PoA nodes on the LAN, one is running Parity 1.5.4 on windows and one is 1.5.4 on OSX.

If I run the Windows first and then the OSX then the two nodes connect and start synchronizing blocks, however if I close the Windows node down and re-run it, it never connects to OSX and OSX never connects to Windows.  Even though both have each other in the network/nodes.json and I even have both nodes pointing to each other with --reserved-peers and --reserve-only, makes no difference.

I also noticed that on both nodes the "failure" count in nodes.json is quite high for both, usually in the thousands.

The LAN is using 192.168.0.x range

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for several months now. It's assigned to @arkpar and linked to the _patch_ milestone.

@slothbag could you state whether this is still an issue with 1.6 or 1.7 branches? Does this only occur if you use PoA? And could you also run the client with `-sync=trace,network=trace` and share the log with us (pastbin or similar)?

**Comment by arkpar** [comment]
Could not reproduce with latest version. Please reopen if you still see this with Parity 1.6.8
