### ISSUE TITLE
Optimise gas calculation in EVM

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#491]
Gas calculation is currently a significant portion of EVM execution time.

Chunk non-externality, non-`JUMPI` instructions together into code segments (EVMJIT does something similar already). Reduce gas only once for each segment.

**Comment by tomusdrw** [comment]
Calculating `current_mem_gas` in `mem_gas_cost` is definitely not need and can take quite signifant time - could be reused between steps.

**Comment by arkpar** [comment]
`mem_gas_cost` is one of the bottlenecks currently.  It can be optimized to use shift instead of division. I.e. use `quad_coeff_div_bits` instead of `quad_coeff_div`

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement it _some day maybe_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by rphmeier** [comment]
We've done the brunt of this with `usize` gas costs and shifts. Chunking isn't done yet but would probably yield pretty major wins, and AFAIK cpp-ethereum evm is still slightly faster. I think the way to do this is at deployment rather than execution time (placing metadata about the code into the DB with it).

**Comment by debris** [comment]
I believe it was sorted out to some degree a while ago by @tomusdrw. I'm closing this issue for now as we have no plans to improve it any further any time soon
