### ISSUE TITLE
Should not be allowed to edit a posted transaction

### ISSUE THREAD

**Issue by CraigglesO** [paritytech/parity#4990]
This is in reference to PR #4949

Should have posted this sooner.

After talking with Tomasz, I don't think you should be entitled to cancel or edit transactions that are already in the network as it would imply that transactions are not technically finite, and people may think they can try to "double spend".

Basically, if tx is already posted, return an error if the removeTransaction function is called.

**Comment by tomusdrw** [comment]
Unfortunatelly it's sometimes required to cancel exactly those transactions that were propagated to other peers (posted to the network).

Cases where such transactions can (and should, that's why we implemented this RPC) be canceled/edited:
1. Transaction with very high gas limit (higher than current block size)
2. Transactions with very low gas price

Such transactions may have been propagated to other peers, but there is a very high chance that they were not accepted and it's safe to remove them from local queue (but the UI should display big fat warning in such cases that it might not work).

**Comment by CraigglesO** [comment]
Theres no better way for certain? The reason I ask is, maybe it's better to actually put limitations (min, max).

And maybe to just auto cancel upon a failed acceptance and simply notify via UI, rather then leave it up to the user to fix?

**Comment by tomusdrw** [comment]
So the problem is that you don't know much about your peers (and other nodes in the network in general, especially the ones that are mining). You cannot tell if the transaction that was propagated to your peer was accepted by it - there is always a chance that some new peer that you'll connect to will accept that transaction. There is also a chance that the transaction will be updated in future, but not now (because gas limit will raise).
So the user should be allowed to send such transactions anticipating the change. Also we have a policy: "informative instead of authoritative" so we try to avoid limiting the power users but giving some details and warnings for others (examples: password validation (done only in ui, rpc accepts everything), sending transaction with too high nonce (impossible in UI, rpc accepts everything), etc.).

**Comment by CraigglesO** [comment]
Perfect. I understand now. Thanks.
