### ISSUE TITLE
Add new 'info' command

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#5020]
Some of the values used by parity may comes from default OS dependant values that may be overwritten by the user through a config file and/or some flags. 
Those values may also change between parity version.

So in the end, it can become challenging to know what are the values *really* seen/used by parity.

I propose the addition of a `info`command that provides just that.
```
parity info
```

This command returns a json object containing the internal config used by parity. For instance:
```
{
   "configFile": "/path/to/config.toml",
    "args": ["identity": "bob"],
     "effectiveConfig": {
      "dbPath": "...",
      ...
   },
   // internal OS based values
   dappFolder: "...",
   ...
}
```

**Comment by grbIzl** [comment]
Instead of additional parameter I'm suggesting to add information about paths to db, dapps and keys used by parity into the output block shown at parity client's startup.
I think, such MVP solution will satisfy the need described in the issue and won't complicate current args structure.
Please let me know, if any other information may be valuable to show there.

**Comment by grbIzl** [comment]
PR https://github.com/paritytech/parity/pull/5904
