### ISSUE TITLE
OnDemand dispatch improvements

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5311]
Currently using `OnDemand` is a bit of a nuisance due to the required network context on all dispatch calls, and it isn't very efficient, dispatching only one request per packet.

A couple of small changes which would go a long way towards addressing this:
1. decouple submitting requests and dispatch to network. this will make chaining results easier.
2. have dispatch fetch groups of unrelated requests at a time when sending to peers (to sidestep the problem of back-reference dispatching for the time being)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since April, neither assigned nor linked to any milestone.

@paritytech/core-devs I see there is a (partial) patch available. Will this make it into 1.7? Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by rphmeier** [comment]
necessary improvements (although not exactly the ones described here) have been made in #5419 and #5573 and this issue will be closed when those are reviewed and merged.
