### ISSUE TITLE
Status difficulty display readability

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5334]
Currently the numbers are not very useful, updating to a formatted display as https://ethstats.net/ (e.g. 1.45TH) would be more user-friendly

![parity 2017-03-29 17-16-16](https://cloud.githubusercontent.com/assets/1424473/24462327/ffd2f97e-14a3-11e7-8079-8b79f2903e72.png)

**Comment by ngotchac** [comment]
Actually Etherstats doesn't format this number, just display the full figure.
Using T/K/M won't be of much help since on Mainnet the difficulty is at `2.5 * 10^20` H currently, which would be `2.5 * 10^8` TH and isn't a lot more readable (and using anything above T is not the common).

![image](https://cloud.githubusercontent.com/assets/2864519/25801136/b2ecc0be-33ec-11e7-99bf-42c83b731902.png)


Feel free to re-open if I'm wrong.
