### ISSUE TITLE
Specific cache for `light::HeaderChain`

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5398]
Perhaps it can just be given a handle to the `LightDataCache` other services share.

@adrianbrink You might be interested in this one, I can mentor.

**Comment by adrianbrink** [comment]
@rphmeier Okay. That would be great :-)

I've opened a PR fix the initial setup and also merged the CLI changes. All tests are still passing.

**Comment by adrianbrink** [comment]
[clabot:check]

**Comment by adrianbrink** [comment]
Should we cache theses things:

- status - &H256 -> BlockStatus
- cht_root - usize -> Option<H256>
- block_header - BlockId -> Option<encoded::Header>

I am asking because the Cache in cache.rs doesn't support those mappings yet.

Should I attempt to make the cache generic (ideally using a macro) or just implement a cache specific to HeaderChain and later on make it generic.

@rphmeier

**Comment by rphmeier** [comment]
@adrianbrink Just headers should be cached for now. The `Cache` has a mapping `H256` -> `encoded::Header`, and headers are stored on disk also keyed by hash. 

Basically, we just need to replace anywhere we go to the DB for headers to first check the cache. If we do go to the DB, it should cache the header after it loads it.

We could cache CHT roots also, but they're really tiny and rarely used, so it's probably not worth the effort for now. 

Computing block statuses should become faster as a result of caching the headers, as we basically just check if we know whether the header exists by looking it up.

**Comment by rphmeier** [comment]
The `Cache` structure is also fine as is, for now. These are the main things which need caching, although we will want to cache recent state values in the future.

**Comment by adrianbrink** [comment]
I've updated the PR.

**Comment by adrianbrink** [comment]
@rphmeier You can close the issue :-)
