### ISSUE TITLE
Parity PPA

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#542]
https://launchpad.net/~infinity0/+archive/ubuntu/rust-beta can be used for dev dependency

**Comment by zmanian** [comment]
I wonder if cargo deb might simplify this process.

Most of the debate here is to be able to package for debian on non-debian systems

https://github.com/mmstick/cargo-deb

**Comment by arkpar** [comment]
Building a debian package is not a problem, we have that already. The main issue here is supporting source build on launchpad.net. PPAs for rustc and cargo are required for this.

**Comment by ethernomad** [comment]
Parity really needs this!

**Comment by pipermerriam** [comment]
This would be a very nice improvement for the install process.

**Comment by elopio** [comment]
PPAs are very insecure both for the user and the developer, because during the installation the maintainer scripts are executed with root permissions. We learned a lot about PPAs here in Ubuntu, so now have a better alternative called snaps, which are secure during installation and execution. The packaging format is a lot simpler than a deb. I made one for parity, you can check it in #5496 .

**Comment by step21** [comment]
Seeing as the default way is manually downloading a zip or deb from the web, I wouldn't really call ppas insecure. Plus they (or generally repos) are the default install method still.
