### ISSUE TITLE
Missing UI icons

### ISSUE THREAD

**Issue by debris** [paritytech/parity#5432]
Latest master, chrome, osx, they are missing on all tabs

<img width="551" alt="screen shot 2017-04-10 at 16 07 06" src="https://cloud.githubusercontent.com/assets/2613714/24851896/f1584b0c-1e07-11e7-94bb-b241bb15388e.png">

<img width="580" alt="screen shot 2017-04-10 at 16 07 01" src="https://cloud.githubusercontent.com/assets/2613714/24851900/f3589970-1e07-11e7-9607-a2532163e8c2.png">

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@paritytech/ui-devs Is it related to #5443? Please, assign this to a developer and decide on a deadline within 7 days or close it otherwise.
