### ISSUE TITLE
web3.site forwards to home.web3.site:8180

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5448]
[Wiki](https://github.com/paritytech/parity/wiki/Parity-Wallet) states that one can navigate to http://web3.site/ in order to access UI but instead it forwards to home.web3.site:8180.

![capture](https://cloud.githubusercontent.com/assets/17831185/24955231/d4e30f12-1f82-11e7-8768-f138beff9d69.JPG)

Going straight to `home.web3.site:8080` works for me. (afaik no custom proxy settings)

**Comment by 5chdn** [comment]
I also noticed a couple of issues here, for example, there are many places that explain users to use `localhost:8080` but this is also blocked.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by trtg** [comment]
Confusion between 127.0.0.1 and home.web3 is more than just an annoyance- it completely breaks the UI. Locally trying to use the token creation dapp, the UI will not load if accessed via 127.0.0.1:8180 with this error:
`
Refused to display 'http://127.0.0.1:8545/ui/tokendeploy.html' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 0.0.0.0:8180 *.web3.site:8180 home.web3.site *:8180".
`
this occurs even if --ws-origins, --ws-hosts, --jsonrpc-hosts,  are set to all and --ui-no-validation are set. In fact, even when combined --with --unsafe-expose it's impossible to access the token creation dapp by clicking through the UI, while using 127.0.0.1:8180

Trying to access via web3.site also fails but for a different reason- it brings up this dialog:
[unable to make a connection](https://i.imgur.com/P3uZYTZ.png)
following the instructions provided in that dialog does nothing and the page remains inaccessible.

**Comment by 5chdn** [comment]
Which Parity version are you using and where do you see the web3 reference in the docs?
