### ISSUE TITLE
ZeroTier, parity network remote access

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5578]
I can't figure out what should be a way to expose parity for external connections.
I've been trying to set it up with some flags in order to allow it working with zerotier.com but no such luck.

Please let me know what parity cli flags I should run with in order to connect externally.

The same problem when I try to use it with EC2+ECS as docker image and forwarding ports. 

Any advice would be helpful, so we can update the docs.

**Comment by tomusdrw** [comment]
Depending what exactly you want to expose it's either:
1. For JSONRPC:
`--jsonrpc-interface all --jsonrpc-hosts all`

2. For Wallet (UI)
`--dapps-interface 0.0.0.0 --ui-interface 0.0.0.0 --ui-no-validation` (NOTE: it's insecure)
More details on *securely* exposing Parity Wallet:
https://github.com/paritytech/parity/wiki/Wallet-Remote-Access

or both of those things.

To have a little bit more control over which interfaces you're listening on you can use IP addresses/domains instead of `all`.

In upcoming release we're planning to add some flags to simplify this.

**Comment by rstormsf** [comment]
Thank you @tomusdrw I will give it a try.
Is there a way to expose both UI and JSONRPC?

**Comment by tomusdrw** [comment]
Sure, just run with all the flags listed there, so `--jsonrpc-interface all --jsonrpc-hosts all --dapps-interface 0.0.0.0 --ui-interface 0.0.0.0 --ui-no-validation` or have a look at the wiki page how to do it in a more secure way.
