### ISSUE TITLE
Unauthorized connection to Signer API blocked

### ISSUE THREAD

**Issue by Darky731** [paritytech/parity#5721]
I've been using Parity for 2 days now, and i noticed it constantly spams this message 'Unauthorized connection to Signer API blocked'. I don't know what it means, but it wasn't causing any trouble so i didn't look into it further. However starting yesterday, my blockchain keeps getting corrupted and causing Parity to crash. I've deleted the blockchain and started over 3 times now, but it keeps happening. I don't know if this issue is related to the message spam, but it's the only clue i got. 

Example of the messages while syncing:
```
2017-05-30 19:33:31  Unauthorized connection to Signer API blocked.
2017-05-30 19:33:33  Syncing snapshot 217/217        #0    0/ 6/25 peers     1 K
iB db    8 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µ
s
2017-05-30 19:33:37  Unauthorized connection to Signer API blocked.
2017-05-30 19:33:46  Unauthorized connection to Signer API blocked.
2017-05-30 19:33:53  Unauthorized connection to Signer API blocked.
2017-05-30 19:33:55  Syncing #3790000 6a0e.e2c6     0 blk/s    0 tx/s   0 Mgas/s
      0+    0 Qed  #3790000    5/ 5/25 peers     1 KiB db  810 KiB chain  0 byte
s queue    8 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-05-30 19:34:01  Unauthorized connection to Signer API blocked.
```
it basically spams these nonstop.

And here is a screenshot of the crash
![crash](https://cloud.githubusercontent.com/assets/16637135/26596945/b29648a2-4570-11e7-84ae-6d9b71c563f2.png)

Anyone have an idea what could be causing this? I'm quite new to Ethereum in general so any help would be welcome.

**Comment by 5chdn** [comment]
Regarding the panic: Your database is corruped. Did that happen more than once? Which version are you using?

Regarding the unauthorized requests: Which OS are you on? Do you have any antivirus or firewalls installed?

**Comment by tomusdrw** [comment]
Do you have Parity Chrome Extension installed?

**Comment by Darky731** [comment]
Thanks for the replies.
@5chdn it's happened 4 times now, i keep deleting the blockchain and starting over, but every time the same issue appears. I'm using 1.6.6.
I'm running Windows 7 right now, no antivirus and i'm just using the default windows firewall.

@tomusdrw I do have the extension installed, but i'm using command line parity (not ptray.exe). I believe command line parity doesn't connect to the chrome extension?

**Comment by ChrisRut** [comment]
I noticed similar messages on my install, I installed parity locally on my laptop (OSX) which installed the Parity extension for me, and then later I installed Parity on a Linux machine and connected to it via SSH tunneling ([as recommended](https://github.com/paritytech/parity/wiki/Wallet-Remote-Access)) from my laptop and it caused these `Unauthorized connection to Signer API blocked.` events on the Linux machines logs, I suspect the extension is tied to my local install of Parity and because I am connecting to a remote machine the extension is attempting to use the token from my local install to connect to the remote machine which isn't going to work for obvious reasons.

Anyone know how to reset the extension, or have the extension support multiple (different) Parity installs?

**Comment by tomusdrw** [comment]
@ChrisRut You can go to extension options and specify different IP address/port of Parity (also remote one).
