### ISSUE TITLE
Parity Wallet stuck on Best Block

### ISSUE THREAD

**Issue by mjbayly** [paritytech/parity#5924]
Hi there - Parity wallet has been stuck on best block for hours. This happened on my home network, now am testing at work am having the same issues. Any idea why? What can I show the community from inside my wallet to helpm troubleshoot? Cheers, Mike

**Comment by keorn** [comment]
How many peers can you see in the bottom right corner?

**Comment by sjd-s** [comment]
I have this issue as well. Four hours ago I had zero peers so i was not concerned but now I have plenty. I still get the warning "unable to reach time API: NTP error, NTP server is not provided"
I checked multiple times and my time clock is perfectly synchronized with time.is so that's not the problem. 
Any ideas how to solve this??

thanks
