### ISSUE TITLE
Use Box<[u8]> instead of Bytes/Vec<u8> for immutable data

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5936]
Reported by Jef, this may significantly lower the memory footprint, cause the `Vec` deliberately overallocates.
Might be good to even change `type Bytes = Box<[u8]>` and introduce `type BytesMut = Vec<u8>`.

- [ ] Accounts (code)
- [ ] Transactions (data)

Also maybe some other immutable `Vec<T>` occurrences would be good to replace (like blooms, traces).

**Comment by NikVolf** [comment]
isn't it just 4/8 bytes of stack space saved (to store allocated cap in [RawVec](https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#47-50))?

any more details from Jef would be nice

**Comment by rphmeier** [comment]
@NikVolf specifically for the case where we want to reallocate a `&'a [T]`, `Box<[T]>` will only allocate exactly what's needed while `Vec<T>` may reserve extra.

**Comment by NikVolf** [comment]
yeah, good point

maybe also consider that some extra heap reserve might actually be a good thing, making length-es of various allocations vary by discrete amount -> less fragmentation

**Comment by Vurich** [comment]
I think just using `shrink_to_fit` is better than using `Box<[u8]>`. As much as the latter enforces that we shrink our data (which is good), there's just way too much code that assumes that `Bytes` is `Vec<u8>`. We don't consistently use the synonym, and a lot of the usages are in generated code. Since I'm working on the transaction queue anyway I can make sure to call `shrink_to_fit` on the input. Having said that, I think we can get some wins by replacing `Vec<Bytes>` with a `JaggedArray` type that stores everything inline behind the scenes. The elements are all immutable, so we can treat it like a stack. We'd just have to have a `Vec<T>` combined with a `Vec<usize>` or some other way to store the lengths.

**Comment by Vurich** [comment]
Related: https://github.com/paritytech/parity/issues/5973

**Comment by folsen** [comment]
Closing unless a profiler tells me this is a really important thing.
