### ISSUE TITLE
Transaction unavailable

### ISSUE THREAD

**Issue by darkorazvoj** [paritytech/parity#5977]
Hi there!

Around 13 hours ago I've sent ETH to an address. Parity showed me the transaction (and the link to etherscan.io) and **took ETH from my balance** but the other party has never received my ETH and etherscan.io cannot locate my transaction entry. Also, the transaction doesn't appear in the Transaction window of Parity. 

Around 20 min ago I've sent ETH to the same address with the same transaction data and gas. Transaction already has 90+ confirmation and I can see it in the Transaction window of Parity.

So, what went wrong with the first transaction? Could somebody help me?

Thanks!

EDIT:
Seems that ETH didn't disappeared. The transaction was canceled or rejected, I'm not sure.

**Comment by tomusdrw** [comment]
Is there anything we can help you with then? Seems that all worked fine.

The transaction might not have been mined because:
1. The gas price was too low
2. It was replaced by the second transaction (sent with the same nonce).

If you cannot see the balance on the second Parity node most likely you are not fully synced:
1. Check the status in bottom right corner
2. Make sure that the time is in sync: https://time.is

Please re-open the issue if you think it hasn't been resolved yet.
