### ISSUE TITLE
When transferring tokens, if there is a comma in the amount it sends 0

### ISSUE THREAD

**Issue by tasdienes** [paritytech/parity#6098]
When using the transfer feature to send tokens to another address, if the amount to transfer has a comma in it (e.g. 1,000), it does not complain, but sends 0.  It should probably either strip out the commas, or complain about it.  Commas are commonly present in amounts when they are copied and pasted from other apps.

**Comment by Nittledai** [comment]
Woah, I almost made that mistake.

**Comment by ThomasdenH** [comment]
In many countries the function of the , and . is switched, so that makes a warning the best solution.

**Comment by 5chdn** [comment]
yes, this should be properly escaped.

**Comment by Vurich** [comment]
Maybe as a solution to the cultural barrier there, we could have an "are you sure?" with the value displayed as "1 ether, 0 wei (1x10^-18 ether)" or something like that. Something utterly unambiguous. This means that if we parse `,` and give it some meaning (either English or international) it doesn't lead to a footgun. We can also reject `,` completely and have the error message specifically state that you should use `.` as the decimal seperator.

**Comment by arkpar** [comment]
Another option is to use local currency separator. https://stackoverflow.com/questions/33561412/hot-to-get-user-s-regional-settings-for-currency-in-javascript-or-jquery

**Comment by Vurich** [comment]
That's a good default, but I think we should still have an unambiguous confirmation dialog. Assumably anyone using our product who would even think to use commas would be bilingual, since the software is English-only/English-first. Some of them may expect the input field to use dot as the decimal seperator because the program is in English (or because that's the standard method to parse integers on the web), whereas others may use commas without thinking. I see non-native English speakers using commas for numbers in English text all the time.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
