### ISSUE TITLE
Use of term "Foundation" to refer to the ETH chain on bottom of main web UI page

### ISSUE THREAD

**Issue by bamos01** [paritytech/parity#6217]
In parity 1.7, the use of the term "FOUNDATION" to refer to the ETH chain on the bottom corner of the main web UI page is both confusing and insulting.  I have never seen this term used before to refer to ETH outside of people who are trolling Ethereum users that ETH is a centralized chain controlled by the EF.  Therefore, when I saw it, I thought I was on a consortium chain and it took me a long time to figure out what it meant.  Can you please consider replacing this name with the clearer and more neutral term like "ETH" or alternatively "mainnet" as is currently used on the wiki page?  'Foundation Chain' is definitely an insult to people who are trying to build ETH as a decentralized project and many contributors do not work for the EF.

**Comment by 3esmit** [comment]
I agree with this, mainnet is the chain that created and funded the ethereum development.
The thing is that Paritytech looks forward Polkadots and does not see any chain as "Main", but I disagree because I see that without ethereum mainnet there would be no Paritytech and no polkadots to be built. 

But this is just a detail... And the worst part is that might be confusing to new users that are not aware about EF, just want to use the Ether they brought at Coinbase.

**Comment by 5chdn** [comment]
It's just a term referring to the network initially realized by the foundation. Key members of Parity were part of that process and they are not using this term to insult anyone.

The idea behind this terminology is to allow easy distinguishing between different main networks. "Ethereum" is ambiguous. "Main Network" even more. Parity supports the following main networks by default:

- Ethereum (ETH)
- Ethereum Classic (ETC)
- Expanse (EXP)

**Comment by bamos01** [comment]
I am specifically requesting abbreviation 'ETH' - this is unambiguous and is not confused with 'Ethereum ' protocol and is not insulting to anyone. Would you consider relplacing derogatory name 'foundation' with 'eth' ?

**Comment by 3esmit** [comment]
@bamos01 if you feel this issue is not solved you need to reopen it.

**Comment by bamos01** [comment]
Thanks I have done so

**Comment by bamos01** [comment]
@3esmit - would you mind asking people at Parity about it?  I'm not getting anywhere- they have provided answer as to why they dont want to use 'mainnet' or 'ethereum' but not much clearer and neutral abbreviations like "ETH" - I think users will be upset once they begin to realize what they have done

**Comment by 5chdn** [comment]
Sorry, assumed this was answered. Reopening.

**Comment by bamos01** [comment]
Thank you- just to be clear my request is to replace the name "FOUNDATION" with "ETH" as the chain name in the bottom corner of the parity UI wallet. 'FOUNDATION chain' is confusing to the average user. It suggests a centralized, consortium chain, and no one (except for people trolling ETH users) uses this term to refer to the ETH chain. In contrast, "ETH" is unambiguous, neutral (with respect to other Ethereum chains), and widely recognized.

**Comment by 3esmit** [comment]
I like MyEtherWallet apporch, it's obviously clear what network you are.
the options are:
ETH
ETC
Ropsten
Kovan
and others.

**Comment by sonulrk** [comment]
Yes, it is confusing. Earlier it was homestead. I'm not aware about trolling "Foundation" but to use "ETH" is better.

**Comment by 5chdn** [comment]
You can modify the chain specification to say ETH rather than Foundation, by just renaming the `name` field, like this: https://gist.github.com/5chdn/a67fe2082d59a07fdaa34c16632742e4

![screenshot at 2017-08-22 14-04-03](https://user-images.githubusercontent.com/15729797/29564649-087aa81c-8743-11e7-8194-989ac02327b9.png)

And then just run `parity --chain eth.json`

**Comment by bamos01** [comment]
This would only fix the problem in my computer. but would not address it for other users.

Would you consider a more general fix?
