### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by terzim** [paritytech/parity#6440]
`bash <(curl https://get.parity.io -L)`

returns

```
dpkg: error processing archive /tmp/tmp.uaVo4gSEPo/parity_1.7.0_amd64.deb (--install):
 trying to overwrite '/usr/bin/ethkey', which is also in package ethkey:amd64 1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/tmp.uaVo4gSEPo/parity_1.7.0_amd64.deb
```

Specifications: Ubuntu 16.04

**Comment by AyushyaChitransh** [comment]
I was not able to replicate this behavior using `bash <(curl https://get.parity.io -L)`. Few searches suggest that it might be possible due to conflicting packages. You should be able to resolve this by 

`sudo dpkg -P ethkey:amd64`

Borrowed from [source](https://askubuntu.com/a/433510/353904)

The installation procedure worked correctly with these specifications:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by 5chdn** [comment]
@terzim do you have cpp-ethereum installed? you should remove that first.
