### ISSUE TITLE
Recovery phrase ?

### ISSUE THREAD

**Issue by avk2** [paritytech/parity#6499]
I first created my wallet with Ethereum Wallet, then I moved to Parity, importing the keystore file + password. 

I saw that Parity can recover a wallet with a recovery phrase. Is this like bitcoin wallets does with 12 word phrase? If so, how can I backup my wallet generating that phrase? I just dont want to keep a json file that can be easily lost.

**Comment by rphmeier** [comment]
When creating your account, Parity gives you a 12-word phrase. If you have not saved it, you cannot generate a new one for the account (because the private key is generated from the phrase, not vice-versa). You can generate a new account and transfer your funds to it if you want one with a phrase. Of course, please guard the phrase carefully. Anyone with access to it has access to your account.

**Comment by avk2** [comment]
Parity had not given me any 12-word phrase when I **imported** the account (I already had one with Ethereum Wallet / Mist and they neither provided me with any phrase). So there is no way to generate that phrase without creating a new account?

**Comment by rphmeier** [comment]
No, there's no way without generating a new account.
