### ISSUE TITLE
Propy (PRO) ERC20 tokens not appearing in Parity wallet

### ISSUE THREAD

**Issue by GelatinousFury** [paritytech/parity#6541]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Windows 10
> - **And installed**: via Installer

I recently bought some Propy (PRO) ERC20 tokens from their ICO.  I sent the tokens from Orderbook.io to my Parity wallet address, and the transaction was successful:

https://etherscan.io/tx/0x93bd3e6a5e832685ae3d497ccbf58e6601e725f3fd2ffaf1de1d0d506c497760

I verified that the receiving address was correct, but I cannot see the PRO tokens within my Parity wallet.  I have never had this issue with tokens not showing up in my Parity wallet before.

I also verified that my Parity wallet was fully synced up.

Any help would be appreciated.  Thanks!

---

**Comment by 5chdn** [comment]
Replied on Twitter :)

https://github.com/paritytech/parity/wiki/Token-Registry

**Comment by GelatinousFury** [comment]
Thanks!

**Comment by Lemon-Essential** [comment]
Hi! I have 72 hours to find my Novalend tokens in my Parity wallet after which they will no longer honor their exchange for new tokens...can you please help me register them in the Parity Token Registry? I am at Duncanjulius9@gmail.com thanx!

**Comment by Tbaut** [comment]
Get in touch on [Gitter channel](https://gitter.im/paritytech/parity), I'll be happy to help. This is an unrelated Github issue ;)

**Comment by pattyoli** [comment]
A friend of mine tried to use the Parity Wallet to recover his Tierion tokens (ERC20) after an ICO, but it didn’t work. He created a new account. After that, He successfully entered the Contract details (incl. contact address) and added the Tierion contract. After following all the required steps, he clicked QUERY. Unfortunately, the result was that he couldn’t see any amount regarding the contract. So, he assumed that  he doesn't have the control or access to his ICO tokens. As a result, he can’t send hisTierion tokens (ERC20) to an exchange by using the command execute. Is it possible to solve this issue? How can this problem can be solve in order to transfer the tolkens to an exchange?﻿

**Comment by Tbaut** [comment]
crosspost @pattyoli, let's sync on gitter
