### ISSUE TITLE
Signer on public node (wallet.parity.io) broken

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6667]

**Comment by 5chdn** [comment]
cc @maciejhirsz

**Comment by maciejhirsz** [comment]
Any details?

**Comment by bjornwgnr** [comment]
The signer doesn't pop up after pressing 'send' button in transfer view.

**Comment by 5chdn** [comment]
Can reproduce with chromium. Was about to take screenshots and it does not allow me to send transactions. The signer is simply not showing up. This needs to be addressed asap.

**Comment by folsen** [comment]
Just tested this as well, nothing shows up in the logs and when you go the signer page it says: "There are no requests requiring your confirmation."

It essentially just silently swallows the transaction and does nothing with it.

**Comment by maciejhirsz** [comment]
So the issue is that the subscriptions aren't emulated on the public node, and the signer is expecting messages coming from the Node instead of handling it within the confines of the browser (as it was intended to happen).

The fix is pretty straight forward but I need to make sure to plug it in the right place that kind of makes sense and doesn't break everything terribly (CC: @jacogr remembers the pain middleware introduced)
