### ISSUE TITLE
Edit, cancel transaction randomly does not work (increments "nonce" sometimes)

### ISSUE THREAD

**Issue by johnerfx** [paritytech/parity#6681]
Parity/v1.8.0-unstable-9196c72-20170918/x86_64-linux-gnu/rustc1.20.0
installed from source code (`cargo build --release`)

Editing or cancelling transaction sometimes does not work. 
It broadcasts new transaction with **'nonce' incremented**. I can't reproduce this easily because sometimes it works just fine and I like to play around with low gasPrice to check if tx gets mined. 
Maybe it would be possible to actually make sure 'nonce' is not incremented performing this such actions(Edit/Cancel)? 
Also console writes 

> "Transaction canceled (hash .........)"

 before I actually have signed the new one. This is a little misleading.

**Comment by 5chdn** [comment]
While this issue is probably valid and I know other users facing similar issues #6666 I would like to ask you to rebuild your client from master daily if you are not running stable or beta releases. Otherwise this will be hard to give you support in such a fast moving environment.

And we are about to move on to a new wallet, so this ticket will be probably never addressed before the new UI is released. But thanks for the heads-up.
