### ISSUE TITLE
Encountered issues with ERC20 token balances & symbols not being displayed within the ACCOUNTS tab

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#6759]
_Before filing a new issue, please **provide the following information**._

> I'm running:  
>
> - **Parity version**: 1.7.6
> - **Operating system**: Windows
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
I thought, if I watched an erc20 contract and have a valid balance for this erc20 token, the token should appear automatically under my "account" on the accounts tab of parity. But it is not. It appeared in v1.7, but i never saw it again with v1.71-1.76. Before with v1.7, I could see the erc20 balance when I clicked on my "Account" and when I clicked on "transfer", I could choose (dropdown) between transfering ETH or my erc20 token. Now this is missing.

Thank you for any solution

PS: To prevent any misunderstanding: This issue/bug relates to the erc20 balance not showing up under the "accounts tab" -> I am not talking about the watching "contracts" tab (there, everything looks fine when I query my balance).

For reference: https://github.com/paritytech/parity/wiki/Tokens here, the 4th picture from the top "Tokens are also displayed in your accounts view next to your Ether balance." shows exactly the bug I am relating to: In my case I would only see the "ETH" balance, but not the "GAV" balance next to it.

**Comment by 5chdn** [comment]
Are you fully synchronized?

Does this persist if you wait a couple of minutes?

**Comment by RSAManagement** [comment]
Same problem, here a screenshoot
![schermata 2017-10-16 alle 10 56 32](https://user-images.githubusercontent.com/32518081/31604022-50711b70-b262-11e7-87b9-9dc0be0d043e.jpg)

**Comment by dip239** [comment]
the same Problem for "Parity//v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0"
fully synced.

**Comment by dip239** [comment]
works in Parity/v1.7.5-beta-822fa82-20171012/x86_64-linux-gnu/rustc1.20.0

**Comment by amal** [comment]
Same error. Two ERC20 tokens (PRIX & YEAR) are not displayed for my account.
Etherscan shows them perfectly.

**Comment by 5chdn** [comment]
Can you please clear your browser cache and test with 1.8.1?

**Comment by RSAManagement** [comment]
I just clear the browser cache (Chromium) and test 1.8.1, same result

**Comment by RSAManagement** [comment]
![schermata 2017-10-21 alle 14 51 05](https://user-images.githubusercontent.com/32518081/31851932-d97aced2-b66f-11e7-86dd-eec4ec3beeb6.jpg)

**Comment by RSAManagement** [comment]
Solved, I run an old Chromium version (Build 56.....) whit the last one it works again, It show me tokens and badges

**Comment by dip239** [comment]
@RSAManagement, @5chdn 
Chromium update (and cache reset) has fixed the issue. Thanx!

**Comment by zumbatan** [comment]
@5chdn 
Are you fully synchronized? Yes always, I encounter this issue often while fully synched

Does this persist if you wait a couple of minutes?  Yes totally! For hours, days (did not switch off Parity 2 whole days), still persisting issue. 

Can you please clear your browser cache and test with 1.8.1?  I am still on 1.76.  But as I understand, this has to work also with 1.76 or not? Have you solved it in 1.8.1?

Thanks

**Comment by 5chdn** [comment]
@zumbatan which browser version?

**Comment by zumbatan** [comment]
chrome 61.0
how can the browser affect this issue  @5chdn  ?

if everything works fine with the watching "contracts" tab , and the query of token balances is fine, it remains very strange why the issue persists within the "Accounts" tab screen.

Have you never observed this issue of not displayed erc20 tokens?
Given the high significance of erc20 tokens and ICOs in the blockchain community, this remains a really annoying bug. Hope we can solve it quickly so that interaction with erc20 tokens is flawless

**Comment by 5chdn** [comment]
Can you open your browser console and check for any errors?

**Comment by 5chdn** [comment]
I closed it because multiple users reported upgrading the browser solved the issue.

**Comment by zumbatan** [comment]
Hi, it is still persisting issue and highly relevant to all of us I think. How can I transfer ERC20 tokens if they are not shown under my account tab?  while this issue is being dealt with,  do you have a temporary  hint for us, how to transfer ERC20 token without the use of the Accounts tab?  

I am now for some days on parity  1.78v  and still the same persisting issue. Again, I am always fully synced with many peers. and still no ERC20 token balance showing up under the Account tab.
I am using latest Browser versions, no addons or whatsoever. 
It also does not work with Firefox apart from Chrome. 

https://github.com/paritytech/parity/issues/6853    this issue is also still persisting under 1.78.  can you look at it please?

Thank you.

**Comment by 5chdn** [comment]
You can still manually execute the token contract to initiate a transfer.
 
> Hi, it is still persisting issue and highly relevant to all of us I think.

So far you are the only one reporting this. Can you open the JavaScript console of your browser ("Inspect") and check for any error messages?

**Comment by 5chdn** [comment]
Screenshot would be nice, too, if possible.

**Comment by zumbatan** [comment]
@5chdn - ok in the console i just see these lines "ReferenceError: event is not defined"  multiple times. nothing else. 

"You can still manually execute the token contract to initiate a transfer."
->please can you give a precise short step by step guide? I mean this is at the end real money, in your parity.wiki there is not such information given. You could easily do mistakes. 

I went to your mentioned "execute" tab-> but for example there are 3 different options "approve"/ "transfer" / "transferfrom" ->what is this about?  How to transfer my erc20 token to another ethereum wallet exactly?

Thank you

**Comment by 5chdn** [comment]
Tracking this in #7024

**Comment by zumbatan** [comment]
@5chdn  @rphmeier   why did you close this issue?
it is still open and me and friends are still experiencing this. it is as you agreed an essential matter since erc20 tokens keep rising in the market. would be nice if you could solve this big issue that erc20 tokens are not displayed  within the "ACCOUNTS" tab.

i can give you now more examples: Golem for example, is shown. But Centra for example not.  I guess, if you figure out why Centra is not shown, then we might be able to solve it by knowing the cause of the error.

What do you think?
---
PS: To prevent any misunderstanding: This issue/bug relates to the erc20 token symbols not showing up under the "accounts tab" -> I am not talking about the "contracts" or "addressbook" tabs

For reference look at: https://github.com/paritytech/parity/wiki/Tokens here, the 4th picture from the top titled "Tokens are also displayed in your accounts view next to your Ether balance." shows exactly the bug I am relating to: In my case, tokens are NOT displayed next to my Ether balance.

**Comment by 5chdn** [comment]
Can you try to clear your localstorage/cache of your browser?

**Comment by ltfschoen** [comment]
I am experiencing similar issues.

**Problem 1:** 
I have both DATAcoin [with DATA symbol](https://etherscan.io/token/0x0cf0ee63788a0849fe5297f3407f701e122cc023) tokens and Datum [with DAT symbol](https://etherscan.io/token/0x81c9151de0c8bafcd325a57e3db5a5df1cebf79c#readContract) tokens.
I have x DATA tokens and y DAT tokens, but in my Wallet view (of the Accounts tab in the Parity Client it only displays that I have x DAT tokens using the Datacoin icon (i.e. it's correctly showing my DATA holdings and their logo, but it's showing the wrong ERC20 token symbol, as it should display DATA instead of DAT). It does not show anywhere in my Wallet view that I have y DAT, even though it shows I have y DAT when I go to https://etherscan.io/address/<MY_ETHEREUM_ADDRESS>#tokentxns

What are the relevant sections of the Parity Client codebase that deal with this, as I would like to try and contribute.

**Problem 2:** 
My Wallet view does not show my Ethereum Classic (ETC) holdings. Is this a feature that we could include that would be look upon favourably? When I go to http://gastracker.io/addr/<MY_ETHEREUM_ADDRESS> it shows my ETC balance since my Ethereum address has money on both the ETH and ETC chains. It would be convenient to see those holdings in the same section as the tokens in the Parity Client.

**Problem 3:** 
I have a holding of the following tokens in my Ethereum address, but none of them appear in my Wallet view of the Parity Client for my Ethereum address:
* [VIU symbol tokens](https://etherscan.io/token/0x519475b31653e46d20cd09f9fdcf3b12bdacb4f5)
* [JOT symbol tokens](https://etherscan.io/token/0xdb455c71c1bc2de4e80ca451184041ef32054001)
* [SET symbol tokens](https://etherscan.io/token/0xe06eda7435ba749b047380ced49121dde93334ae)
* [GZE symbol tokens](https://etherscan.io/token/0x8c65e992297d5f092a756def24f4781a280198ff)
* [COV symbol tokens](https://etherscan.io/token/0xe2fb6529ef566a080e6d23de0bd351311087d567)
* [LEIA symbol tokens](https://etherscan.io/token/0x96e2ffddd5aab73def197df5fdc4653a72976837)
* [INSP symbol tokens](https://etherscan.io/token/0x52903256dd18d85c2dc4a6c999907c9793ea61e3)
* [CAT symbol tokens](https://etherscan.io/token/0x68e14bb5a45b9681327e16e528084b9d962c1a39)

The only tokens that I know successfully appear are:
* ETH, COB, LRC, OMG, DOT, QSP, RDN, WRC

What are the relevant sections of the Parity Client codebase that deal with this, as I would like to try and contribute.

**Problem 4:** 
Some tokens such as INSP are just Promo tokens that provide a discount when investing in an ICO, but after the ICO has ended they may no longer serve any purpose, so whilst we may be transferred that token, we as users may want to "hide" it from the Wallet view in the Accounts tab of the Parity Client manually ourselves after a certain date. 

Would adding a feature that allows users to toggle the state of whether certain tokens are visible or not be looked upon favourably? 

What are the relevant sections of the Parity Client codebase that deal with this, as I would like to try and contribute. 

**What's your Parity version?**
* Parity//v1.8.4-beta-c74c8c1-20171211/x86_64-macos/rustc1.22.1
* Note: I had the same issue with Parity v1.8.3-beta

**What's your operating system and version?**
* macOS Sierra 10.12.6
* Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)

How did you install parity?
* Downloaded https://parity-downloads-mirror.parity.io/v1.8.4/x86_64-apple-darwin/parity-1.8.4-macos-installer.pkg
* Validated checksum with `shasum -a 256 parity-1.8.4-macos-installer.pkg`
* Run parity-1.8.4-macos-installer.pkg

Is your node fully synchronized?
* Yes, fully synchronised

Did you try turning it off and on again?
* Yes, I've restarted Parity, restarted Google Chrome, and emptied browser cache with hard reload

**Comment by zumbatan** [comment]
@5chdn  my browsers do this automatically for each new session...
have you tried to add Centra token in your client for windows? Try it if possible, to figure out whether this is a global issue or not.

**Comment by zumbatan** [comment]
@5chdn  @rphmeier   HI, do you have any new information for this issue? Thx

**Comment by 5chdn** [comment]
@zumbatan is centra registered with the token registry? https://github.com/paritytech/parity/wiki/Token-Registry

You are saying:

> Golem for example, is shown.

Of course, you need to register it :)

**Comment by zumbatan** [comment]
@5chdn  @rphmeier   Hi , why did you close this highly relevant ERC20 token issue?
Centra is registered in the token registry! And as I said this issue relates NOT only to one token, but to many different registered erc20 tokens! Centra is just one example!

So please open this again, and have you already tried yourself to reproduce the issue? ::
"have you tried to add Centra token in your client for windows? Try it if possible, to figure out whether this is a global issue or not. (Centra is not the only affected token, but we can work with centra as example, because I imagine they all have the same failure cause)"

Please try to give new information to this issue, thank you very much!

**Comment by zumbatan** [comment]
@5chdn  , thanks, greatly appreciate you re-opening and modifying it! 
you guys have the best eth wallet ever, and really hope that it evolves more secure and automatically displays ANY erc-20 token (where the user has a balance >0) within the "account" tab view .

**Comment by hyvaa** [comment]
I am experiencing same problem.
Running v1.7.13 and it was woking well ( showing tokens) and one day the tokens were invisible.
I am running Parity all the time, and chain is alway fully syncing.
I have tried resetting the chain and Parity upgrade, but tokens are not appearing.
(Surely they are checked in EtherScan.io)

------------------------
I'm running:

Parity version: v1.9.0 v1.8.7 v1.7.13 (all versions same problem)
Operating system: Windows8.1 64
Chrome : v64.0.3282.119 (64)
And installed: via installer

**Comment by 5chdn** [comment]
Yes, all versions are affected, parity 1.9.1 will fix this issue (and 1.8.8 probably).

**Comment by zumbatan** [comment]
@5chdn   hi, why are you closing this OPEN UNSOLVED issue again?  What kind of dedication is this to a persisting global issue to such a important erc20 feature?

You should close this when there is a valid solution .  People will migrate to another erc20 friendly wallet if nothing is done, erc20 tokens are getting even more important than eth itself in the wake of ICOs, so this should be of high priority from market demand point of view (of course, lower prio than security)

**Comment by 5chdn** [comment]
1.9.1 released!

**Comment by zumbatan** [comment]
@5chdn   @hyvaa 
this issues still is OPEN and persisting , also in the most current versions 188,191,192!! 

please take a look again, highly strange why this automatic displaying of erc20 coins is not working.

what is the failure cause??

**Comment by 5chdn** [comment]
No sorry, please try to find any other wallet that does that properly.
