### ISSUE TITLE
List of error codes and their meanings

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6766]
Is there a list of Parity error codes and what they map to?  Something like this HTTP error code table, but for Parity error codes:
https://www.lifewire.com/http-error-and-status-codes-explained-817986

If I had such a thing, I could debug many more errors myself, like this ticket:
https://github.com/paritytech/parity/issues/6765

**Comment by tomusdrw** [comment]
You can find a list of possible errors here: https://github.com/paritytech/parity/blob/b0c15497e110f3c9d70be067b6294188e682e8a8/rpc/src/v1/helpers/errors.rs#L25-L48

**Comment by stone212** [comment]
@tomusdrw Thank you but I think you misunderstood the question.  Maybe I should make it more clear.  I am not asking for a list of error codes and the short title, but a list of the error codes and an explanation of what they mean.  For example, here is a list of HTTP error codes.  The top section just lists them, like the link you sent.  Then the rest of the page explains them.  So a person can read these explanations and know what the error codes mean.  Then he can memorize the titles as well and he is then knowledgeable on the subject.

**Comment by stone212** [comment]
@tomusdrw Is there a way to re-open this or should I re-post?

**Comment by tomusdrw** [comment]
The explanation is provided in the error object itself, the error codes just map to some class of errors and you can find more details in `message` and `details` fields of the error code.
Feel free to look at the code and document that part in the wiki pages.

**Comment by tomusdrw** [comment]
The error in #6765 provided you with all the details you needed. Some RPC call that was invoked had invalid params (the error code is even part of the JSON-RPC spec, not our custom one).

And the details were mentioning that one of the parameters was supposed to be `a hex-encoded hash with 0x prefix`. You need to inspect the exact RPC call that truffle is making and figure out which parameter is malformed.

**Comment by stone212** [comment]
@tomusdrw 

> you can find more details in message and details fields of the error code

Where can I find these fields?  I am not looking at the error message right now so maybe it is a stupid question but I want to ask while this is still ongoing.

>  that one of the parameters was supposed to be a hex-encoded hash with 0x prefix. You need to inspect the exact RPC call

Aha!  Do you realize what you just skipped over here?  Saying "one of the parameters was supposed to be a hex-encoded hash with 0x prefix" is just as meaningless as the original error from https://github.com/paritytech/parity/issues/6765 which is:

> [-32602] Invalid params: expected a hex-encoded hash with 0x prefix.

"one... parameter" or "expected a hex-encoded hash" could mean absolutely anything!  But you gave me useful information when you said it has to do with the RPC call.  If we put these together, we have a new error message:

>  [-32602] Invalid params: one of the parameters received via RPC was expected to be a hex-encoded hash with 0x prefix

Do you see how the original message and your summary of it are not useful for debugging, but mine is?  You say "there's a thing which exists that is yellow and should be green" and I said "there is a car coming down the Avenue that is yellow and should be green".  

Ticket https://github.com/paritytech/parity/issues/6765 would not be as necessary if the error message was written better.

 If you can fix this error message, and make fixes to any/all others that are equally poorly written at present (which I offer to help with), then the answer to this ticket here would simply be a link to a file that lists the error code and error message next to each other.

**Comment by tomusdrw** [comment]
Parity deals only with RPC - the only way to communicate with the node is via RPC. Errors are returned in context of an RPC call so adding `one of the parameters received via RPC was expected to` is a bit redundant in my opinion.

I think the issue is that you got this error not while making an RPC call but rather when using a library (truffle) that hides this complexity from you, but is just displaying the exact same errors returned from RPC. The error codes and messages are meant to be low-level, the libraries are free to display more meaningful messages based on the code.

An example of invalid RPC call:
```
$ http localhost:8545 jsonrpc=2.0 id=1 method=eth_sendTransaction params:='[{"data": "5155"}]'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 24 Oct 2017 07:59:10 GMT
Transfer-Encoding: chunked

{
    "error": {
        "code": -32602, 
        "message": "Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length."
    }, 
    "id": 1, 
    "jsonrpc": "2.0"
}
```

And parity logs with `-lrpc=trace`
```
2017-10-24 10:00:17   TRACE rpc  Request: {"jsonrpc": "2.0", "id": "1", "method": "eth_sendTransaction", "params": [{"data": "5155"}]}.
2017-10-24 10:00:17   DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length."},"id":1}.
```

You can clearly correlate the invalid request and the error response from `-lrpc=trace` logs that's why we asked you to provide them.


> If you can fix this error message, and make fixes to any/all others that are equally poorly written at present (which I offer to help with), then the answer to this ticket here would simply be a link to a file that lists the error code and error message next to each other.

You can find most of the possible error messages in that file: 
https://github.com/paritytech/parity/blob/b0c15497e110f3c9d70be067b6294188e682e8a8/rpc/src/v1/helpers/errors.rs 
Deserialization errors can be found here:
```
grep -re "Error::custom" rpc
rpc/src/v1/types/derivation.rs:			v => Err(Error::custom(format!("invalid derivation type: {:?}", v))),
rpc/src/v1/types/block.rs:			Err(S::Error::custom("Unserializable structures: expected objects"))
rpc/src/v1/types/index.rs:				Error::custom(format!("Invalid index: {}", e))
rpc/src/v1/types/index.rs:				Error::custom(format!("Invalid index: {}", e))
rpc/src/v1/types/pubsub.rs:			.map_err(|e| D::Error::custom(format!("Invalid Pub-Sub parameters: {}", e)))
rpc/src/v1/types/filter.rs:			.map_err(|err| D::Error::custom(format!("Invalid variadic value type: {}", err)))
rpc/src/v1/types/bytes.rs:			Ok(Bytes::new(FromHex::from_hex(&value[2..]).map_err(|e| Error::custom(format!("Invalid hex: {}", e)))?))
rpc/src/v1/types/bytes.rs:			Err(Error::custom("Invalid bytes format. Expected a 0x-prefixed hex string with even length"))
rpc/src/v1/types/block_number.rs:				Error::custom(format!("Invalid block number: {}", e))
rpc/src/v1/types/block_number.rs:			_ => Err(Error::custom(format!("Invalid block number: missing 0x prefix"))),
```
Feel free to submit PR improving these error messages. I'm also very open to improve the errors by providing the exact field name which failed during deserialization if there is any way to do that in `serde`.

**Comment by stone212** [comment]
@tomusdrw 

> Parity deals only with RPC - the only way to communicate with the node is via RPC.

(a) This the first time I heard that, and I have been using Parity for six months.  So the assumption that someone would automatically know this is not a reasonable one.

(b) I still don't believe it, because there is also UI and WS.  And since the error came through the UI, I could imagine the error being any of these three, or something completely unrelated to communication.  There is no way to know without a meaningful error message
> I think the issue is that you got this error...

I will respond to this in the thread for https://github.com/paritytech/parity/issues/6765.

> Errors are returned in context of an RPC call

Then the documentation page that I am recommending (and happy to participate in) should say that at the top.  As in "The following list of error codes are returned in the context of an RPC call:"  In that case, you would be correct that mentioning RPC in each error message would be redundant.

> You can clearly correlate the invalid request and the error response from -lrpc=trace logs that's why we asked you to provide them.

I believe you.  And it helps that 22 hours ago when you mentioned that the error was related to RPC, as that was not my first guess.   As I mention in the other thread, I will try this again when I can. 

> You can find most of the possible error messages in that file:

You've posted that file before.  I've explained why it is inadequate for this issue.  I even gave examples.

> Feel free to submit PR improving these error messages. 

I genuinely thank you for taking time to respond.  But I can't resist a little pushback to that one.  My responsse is:  And you should feel free to stop assuming I can read your mind by magically knowing that the errors relate to RPC and by using obscure abbreviations like "PR".  If there is some significance to that abbreviation that you think would allow me to help you make improvements, feel free to share this secret.

**Comment by tomusdrw** [comment]
Sorry for misunderstanding, I was approaching this issue in a bit too technical way because I misread the information the you got the error in the UI not in the truffle output.

Just for clarity let me explain my reasoning:

- The RPC is available over various transports: HTTP, WebSockets and IPC and it's the only way to communicate with the node
- The UI (Parity Wallet) is communicating with the node using RPC over WebSockets.
- External libraries (like truffle) are communicating using RPC as well.
- The error codes and messages I posted are the ones returned by RPC, so that's why they don't mention this context explictly
- I mentioned that libraries (and in general consumers of the RPC) are encouraged to present more meaningful messages to users by checking the error code.
- Although the UI is just displaying the raw messages returned by RPC without a context and that indeed might be confusing.
- Since UI should never really produce invalid RPC requests the error message should never be displayed and that seems like a bug (let's continue discussions on that issue in #6765)

I'm open for documenting possible error codes and the context in which the may occur, that's why I proposed you to submit a github Pull Request (PR) with additional documentation or errors rephrasing. Also feel free to work on a wiki page. Re-opening the issues to keep track of the efforts.

**Comment by stone212** [comment]
@tomusdrw 

> Sorry for misunderstanding

Not a problem.  That is what this is for.

> Although the UI is just displaying the raw messages returned by RPC without a context and that indeed might be confusing.

*This* is the heart of this issue that I opened and I am happy that you added it to the documentation queue.  Basically what happened is that since the RPC error without context is confusing, I searched for documentation.  But I found none, so I opened the ticket.

A suggested solution that might make it unnecessary to have a separate doc like I initially suggested: Simply make each of the RPC errors read: 

> [-32602] RPC Error:: Invalid params: one of the parameters received  was expected to be a hex-encoded hash with 0x prefix

or:

> [-RPC-32602] Invalid params: one of the parameters received  was expected to be a hex-encoded hash with 0x prefix

In either of those cases, a user would think "ah!  I have an RPC error" and I would search for "Parity RPC howto debug" and hopefully would learn about -lrpc=trace.

> Also feel free to work on a wiki page.

I am very happy to help with the few items I understand.  But I still know so little that I can only offer broad suggestions and then specifics about items after I learn about them (as above).

And yes, let's discuss the actual issue in https://github.com/paritytech/parity/issues/6765

**Comment by folsen** [comment]
@Tbaut Could you see if we could add a wiki page with RPC error codes and their layman explanation?

**Comment by Tbaut** [comment]
Logged it here: https://github.com/paritytech/wiki/issues/115

**Comment by stone212** [comment]
@Tbaut I am not sure what you logged.  It seems that what you did was create a new Issue that basically links back to the page that was so inadequate that I opened this Issue originally.   

This page needs two things to be useful for anyone other than a dev who already knows the answers:

1. Provide actual, layman explanation of the RPC error codes.  Some of the comments in that code are useful.  Others are not.  Please look back to my reply to Tom on Oct 24, 2017 and you will see what I mean.

2. If this is really user-readable then it will be useful for anyone who uses the UI and is not a dev.  In that case it also has to be findable.  Is there a page on the wiki under RPC that links to this?

**Comment by folsen** [comment]
@stone212 We have changed around the way we handle our wiki and it is now community contributable, we are tracking documentation issues on the repo for the wiki instead of in this repo. Having it tracked there indeed doesn't mean that it's done, it just means that we're now tracking it in a place where it's less likely to get lost.

**Comment by stone212** [comment]
> our wiki and it is now community contributable

Oh!  Then I will write more and complain less.
