### ISSUE TITLE
eth_estimateGas result too high

### ISSUE THREAD

**Issue by littleskunk** [paritytech/parity#6867]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity 1.8.1-beta
> - **Operating system**: Windows
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**expected behavior**
I would expect that estimateGas is giving me the exact gas amount.

**actual**
At the moment estimateGas is always to high.

https://etherscan.io/tx/0x1742b61ab34ed15e7595595bd472a946abd8b5d6800e8c5026b1b579d298989e

**steps to reproduce**
Code block to try it yourself. In this case estimateGas returns 51752.
```
'use strict';

const Web3 = require('web3'); //1.0.0-beta.18
const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545', 0));

const erc20Contract = '0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac';
const erc20ABI = [
	{"constant":true,
		"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf",
		"outputs":[{"name":"balance","type":"uint256"}],"payable":false,"type":"function"},
	{"constant":false,
		"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer",
		"outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"}];
		
const erc20 = new web3.eth.Contract(erc20ABI, erc20Contract);
		
web3.eth.estimateGas({
	from: '0x81c642837024259ce40c2098f792eea2aee865f3',
	to: erc20Contract,
	value: web3.utils.fromDecimal(0),
	data: erc20.methods.transfer('0x6957D7493c7Fa1b1a9fcBd60E509137d0E0fd3F6', web3.utils.fromDecimal(393386904)).encodeABI(),
	gas: web3.utils.fromDecimal(150000),
	gasPrice: web3.utils.fromDecimal(1),
	nonce: web3.utils.fromDecimal(2)
}).then(console.log);
```
---

**Comment by rphmeier** [comment]
The UI adds a ~20% additional extra gas to the result of estimation. This should be capped at some constant maximum, since for high-gas transactions it leads to a lot extra being sent.

**Comment by littleskunk** [comment]
I am not using the UI. I am using web3. I would expect a 100% acurate result.

Please take a look at the linked transaction. The result is more than 60% too high!

**Comment by rphmeier** [comment]
> I would expect a 100% acurate result.

not possible since the programs are turing complete and state can change in unpredictable ways between the state at estimation and at inclusion in the chain.

**Comment by littleskunk** [comment]
And why is the result 60% off? I would like to get the estimate gas as acurate as possible and than send out the transaction more or less at the same millisecond. Don't add any additional gas. That is my job. API should be acurate and the UI or my script can add 60% if that is realy needed.

**Comment by 5chdn** [comment]
The JSONRPC API returns the estimated value to its best knowledge.

**Comment by littleskunk** [comment]
I would not call that "best knowledge". On the one side you are telling me that the result can't be 100% accurate and on the other side the result minus 15000 is a perfect match at the end. I checked a few transactions. The difference is always 15000.

I would love to help debuging this as good as I can. Let me know if you are interested.

**Comment by 5chdn** [comment]
Yeah, sure, if there is room for improvement, it's much appreciated!

**Comment by littleskunk** [comment]
I run some tests with `trace_transaction`. It will print out same used gas. Even the full Output `stateDiff` is showing the wrong used gas.

`vmtrace` is available on etherscan:
https://etherscan.io/vmtrace?txhash=0x1742b61ab34ed15e7595595bd472a946abd8b5d6800e8c5026b1b579d298989e&type=parity

In this case `"gasUsed": "0x3578"` -> 13688 + 21000 = 34688. That result is wrong. It should be 21752.

I have problems to understand the output of `stateDiff`. I will have to read some manuals first.

**Comment by gituser** [comment]
Why close this issue if it's not resolved?

I'm having exact same issue, except `eth_estimateGas` can return 3x or 20x more gas than actually required. It's completely random and can happen at any time.

All my testings were on ropsten testnet and `eth_estimateGas` varies wildly. I'm passing exactly the same transaction options as to the `eth_estimateGas` call as I do to `eth_sendTransaction` method to send out the actual transaction.

Transaction is very simple: transfer X amount of ERC-20 tokens from one address to my coinbase address. Coinbase address never changes.

This is a serious issue because it's not possible to use `eth_estimateGas` at all to calculate possible gas usage to top-up certain account in order to transfer ERC-20 tokens or any other type of tokens.

**Comment by joshua-mir** [comment]
> not possible since the programs are turing complete and state can change in unpredictable ways between the state at estimation and at inclusion in the chain. Parity binary searches for the lowest amount of gas that succeeds at the state of the best block at the time of estimation.

The best advice here is that you should only use estimateGas as a minimum anyway, and perhaps round up to the next order of magnitude. The issue is that if a contract has logic that reverts early in execution the cheapest transaction would be used for the estimate. If you have suggestions on better ways to do this, we're open to them, as mentioned earlier.

**Comment by gituser** [comment]
>The best advice here is that you should only use estimateGas as a minimum anyway

I'm sorry but it's not suitable as a minimum at all - the call produces quite often values way above the required minimum of Gas.

E.g. transfer function of typical ERC-20 contract requires either 21464 or 21528. `eth_estimateGas` sometimes gives values around 300000. 

My task is quite simple: I got some tokens on empty ETH account I need to top-up the account to transfer those tokens to my coinbase address. So basically I need to calculate exact amount of ETH I need to transfer to that address in order to perform 1 transaction.
