### ISSUE TITLE
Parity won't detect Ledger Nano S unless it is plugged in when Parity starts.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6873]
> I'm running:
>
> - **Parity version**: 1.8.0
> - **Operating system**: Windows
> - **And installed**: via installer

---

If I have Parity running and I plug in my Ledger Nano S and open the Ethereum app, Parity doesn't seem to see the Ledger.  However, if I exit Parity and then re-launch it with the Ledger plugged in, it works fine.

**Comment by Diti** [comment]
Same issue on `Parity//v1.8.1-beta-0e4a06d-20171020/x86_64-macos/rustc1.20.0`.

**Comment by 5chdn** [comment]
@folsen can you try to reproduce this?

**Comment by folsen** [comment]
Yes, I probably won't be able to immediately, but I'll assign myself and do it when I have time. I'm suspecting it's a Windows USB issue actually. We look for new devices when the HID api detects a new device connected, but the Ledger doesn't actually exist on USB connection, it only "exists" once you've entered the app. If this is the case, then there's not much we can do about it (without retooling the whole way we detected HW wallets) since it's a limit in Windows.

Will look into it to confirm whether I'm right or wrong.

**Comment by Diti** [comment]
@folsen I pasted my version information above to say I have the same problem in macOS. I donʼt think it is a Windows-related issue.

**Comment by folsen** [comment]
@Diti ah, sorry, I missed that. Then it's much stranger than I expected because I definitely don't have that on my Mac. I'll have to dig a bit deeper then to try to reproduce. Do you have a second Ledger or maybe a Trezor attached? Are they attached through USB hubs or anything else like that that might cause a delay in boot-time of the device?

**Comment by MicahZoltu** [comment]
Mine is attached through a 4-port USB hub with nothing else plugged in or with my cell phone (Android) plugged in and charging (same problem in both cases).  This is an Windows.

**Comment by folsen** [comment]
@MicahZoltu can you do me a favor and test it without the USB hub to confirm it still happens?

**Comment by MicahZoltu** [comment]
I just verified without the hub, same problem.  Even if I plug the Ledger in just after restarting Parity, Parity doesn't recognize it.  It must be plugged in when Parity launches.

I'm determining that the ledger is not connected based on whether my Ledger account in the UI is greyed out or not.  If there is a more authoritatize way to test let me know.  Wait doesn't appear to help either.

**Comment by folsen** [comment]
@niklasad1 Can you confirm or deny whether the new USB stuff fixes this?

**Comment by niklasad1** [comment]
@folsen I will check this next week when I'm back in Berlin with access to a `Ledger`

@MicahZoltu meanwhile If you could run ```parity.exe -l hardware_wallet=trace``` and provide the log that would help too!

**Comment by Tbaut** [comment]
Tested successfully with parity UI 0.2.5 and v1.11.1
