### ISSUE TITLE
Does not return blocks and transactions for old blocks after warp sync

### ISSUE THREAD

**Issue by izetex** [paritytech/parity#6922]
I'm running:

**Parity version**: 1.7.5
**Operating system**: MacOS
**And installed**: via  homebrew 

After node fully synced, i try to use RPC to get data on old transactions and blocks, and it returns nothing. Only blocks of several days ago and new transactions are returned OK.

I did not use flag  --no-ancient-block, so all old data must be synced, right? 
It does not

---

**Comment by Office-Julia** [comment]
Hello. Let me assist you with this issue. 
Have you tried different way of installing / running parity? 

Please note version 1.8.1 is not the latest one.
Our latest Beta release is 1.8.2,
and latest stable release is 1.7.8.
Please kindly let us know if you tried to install these versions and if the problem happens there again?

Reference: https://github.com/paritytech/parity/releases

**Comment by Office-Julia** [comment]
Fething old blocks takes quite a long time (note that any warp sync in the meantime will remove previously fetched blocks).
Encrypted by an unverified device
The progress can be seen by log lines with yellowish block numbers.

This is expected behaviour, not an issue. Node just downloading ancient blocks and it takes a while.

**Comment by izetex** [comment]
I do not see any "yellowish" block numbers in logs.

How can i get the status of ancient blocks through API ? Or looking in logs?

**Comment by 5chdn** [comment]
for old transactions, you need to enable transaction tracing.

`--tracing on`
