### ISSUE TITLE
Possible solution

### ISSUE THREAD

**Issue by BenKaufman10** [paritytech/parity#7005]
As the Ether still exists but just unmovable, is it possible to issue a new ERC20 token which will represent ownership over a locked Ether in 1:1 proportion?
This can simulate “moving” the locked Ether without  unfreezing them. (At least until a hard fork).

Can this be a decent (at least temporary) solution for the locked Ether problem?

**Comment by EliasZ** [comment]
Good luck convincing everyone that your token is worth 1 ETH.

**Comment by BenKaufman10** [comment]
It's representing 1 real ETH. It can be used almost the same way as regular ETH.
I now it's complex psychologically but I think it can technically work

**Comment by AdamSLevy** [comment]
How will the contract guarantee that the token will be redeemable for a locked ETH? Barring that no one will accept it.

**Comment by BenKaufman10** [comment]
It should be a temporary solution...
Anyway, it shouldn't matter, it should represent the right on existing ETH.
It's a bit like colored coins, it just represent ownership on something that can be directly movable on the blockchain.

**Comment by jazzyjackson** [comment]
It is a funny problem, say you launched your bar of gold into space (frozen, unrecoverable) but still have the piece of paper that proves your ownership of the bar of gold.

I don't think anyone will accept your ownership of an irrecoverable asset.

**Comment by ThatOtherZach** [comment]
"ParityBucks"
  
It might work, but I'd think it would work best as a solution for Parity to "give back" the ETH locked away. Basically have a contract that checks if the owner owns a multisig address, if so issue X number of tokens for the locked ETH.

These tokens can then be sent to another contract that would send back ETH for either a full refund or modest compensation. This ETH refund would of course have to come from Parity themselves as making a tradeable token would get rekd on the open market.

Obviously not a regular ERC20, it would only be able to be held by the affected owners address and only tradable with the "refund contract". Not sure if that's possible, but I think it's a good idea as a last resort. No fork, Parity would look like a hero, but it would not be a cheap endeavor.

**Comment by ericchenmelt** [comment]
If the fork is confirmed then its a viable solution for the owners to get temp eth. Almost like a future contract.

**Comment by chris-blockunity** [comment]
simply adding a provision that the locked eth needs to have a 1:1 pre-signed transaction posted to the blockchain that redirects the [in the future, unfrozen eth] to the smart contract that can then transfer it to the eventual owner of this token.

you could also attach forward bonding to this system, where the individual (collateralizing) their frozen eth must also post an equivalent value in eth to the contract, that is locked until the unlock occurs. at this point if the pre-signed transactions are not double spent the bond is returned, and if it was double spent (the pre-signed transaction doesn't complete because the original owner attempted to transfer out to another address) then the collateral is forwarded to the address that the pre-signed transaction has as the destination.
