### ISSUE TITLE
(Question) When SYSTEM_ADDRESS is calling `finalizeChange` it doesn't fire any events

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7141]
https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/contracts/PoaNetworkConsensus.sol#L102
```js
        ChangeFinalized(getValidators());
```
this event is never fired, although the calls are executed by SYSTEM_ADDRESS

**Comment by rphmeier** [comment]
Hey, sorry for missing this one before. It's because the `finalizeChange` function is currently an extra-transaction call (like the proposed `BLOCKHASH` changes -- this is also why we use the same `SYSTEM_ADDRESS`). There are no corresponding transaction or receipt objects for such calls, so they don't provide log events.
