### ISSUE TITLE
Factory Contract creating another contract

### ISSUE THREAD

**Issue by TheFoodGuy** [paritytech/parity#7186]
Hey Guys, 

I'm pretty much a beginner in parity and ethereum in general so bear with me

 Basically, I have a source file with two contracts, one being the factory contract that creates the transaction contract. I was able to execute successfully the creation of the transaction contract but I have no idea how to access said contract. I do have the address of the contract and that one of my accounts is the owner of it. How do I go about getting access?  
(if there is a documentation on parity about it, my bad, I just could not for the life of me find it)
Thank you!

**Comment by rphmeier** [comment]
@TheFoodGuy I'm not sure what the transaction contract you mean is, but I'll try to answer regardless.

Contracts will expose methods and other functionality publicly, but in order to interact with them you need two things:
  1. the address where the contract instance is deployed
  2. the contract's ABI (which describes public methods and how to construct transactions or calls to them)

In the Parity interface you can "watch" a contract by putting in these two items, which will then let you interact with it.

In solidity if you have a contract type `MyContract`, you can create an object of type `MyContract` by deploying a child contract. I think this is what you have already done. You can cast this object to an `address`, and expose the address publicly somehow (either through a log event or public method on the "factory" contract). The solidity compiler or your development tools (like remix) can give you the ABI for `MyContract` or any other contract types you compile with it.
