### ISSUE TITLE
Problems with snap

### ISSUE THREAD

**Issue by robbiehanson** [paritytech/parity#7254]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.0-unstable-fcddc77-20171208/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: via `sudo snap install parity --edge`
> - **Are you fully synchronized?**: not yet
> - **Did you try to restart the node?**: n/a

Prior to switching to `snap`, I was using the simple one-liner install. Which means that prior to switching to snap, I had my `config.toml` file & all data stored in:

- ~/.local/share/io.parity.ethereum

However, after switching to snap, I eventually noticed that the locations had changed to:

- ~/snap/parity/[number]/.local/share/io.parity.ethereum

I tried to tell parity to use a custom base-path, but that doesn't work:

```
$ parity --base-path=/home/robbie/datadrive/parity
Error upgrading parity data: CannotWriteVersionFile
```

I tried giving parity permission via snap, but that didn't work either:

```
$ sudo snap connect parity:home
error: snap "parity" has no plug named "home"
```

To make matters even worse, the current snap system appears to be leaking data like crazy ! From what I can tell, everytime snap auto-refreshes parity, I get a new copy of the entire blockchain !

```
~/snap/parity$ du --max-depth=1 -h
1.9G	./6014
4.0K	./common
13G	./6023
11G	./6209
26G	.
```

What's the solution to this problem ?

**Comment by 5chdn** [comment]
The idea of having snaps is to introduce a whole lot of redundancies, why did you switch to snaps in the first place? Can't you attach the snap to your previous id?

Maybe @elopio can help you with this.

**Comment by robbiehanson** [comment]
> The idea of having snaps is to introduce a whole lot of redundancies

Are you trying to say that "the point of having snaps is to make a whole bunch of copies of the ethereum blockchain data" ?

Because I can't imagine that's what you're implying. But, as I pointed out, this is what the current snap solution is doing.

> why did you switch to snaps in the first place

- I have never been able to get parity's autoupdate feature to actually work. (Yes, it's enabled.)
- The one-liner install still points to an old version.
- Snaps solve the autoupdate problem.
- Snaps solve many other problems (permissions , different linux distros, etc)

> Can't you attach the snap to your previous id?

I'm not a snap expert. I don't know what you mean by this.

> Maybe @elopio can help you with this.

That would be great, although you've already closed this issue.

**Comment by elopio** [comment]
@robbiehanson, to let you write to /home/robbie, we would have to add the `home` plug in the snapcraft.yaml. That's doable, but well, it opens the door for any other snaps that have the `home` plug to read your wallet. I didn't want to do it before being sure that people would need it.

About the duplicated data, that's what allows the rollback when a snap update goes wrong. If you have all the info backed up, you can get back to a previous version without any additional work. When the snaps have information that they don't want to backup, they can save it to $SNAP_USER_COMMON instead of $HOME/$SNAP_USER_DATA. Again, this is a change that should be done before discussing because it could introduce complexity. For example, if between revision 1 and revision 2, the format of the data stored in $SNAP_USER_COMMON changes, then a revert to revision 1 requires extra handling to convert the new data, or to mark this revert as forbidden, or to wipe out the data and start from scratch. All of these options are being done by various snaps out there, so it's doable, just requires some thinking.

I'm happy to help with whatever you decide to implement.

**Comment by robbiehanson** [comment]
> it opens the door for any other snaps that have the home plug to read your wallet

That makes sense. For now I've modified my system so /home/robbie/snap is on the proper disk.

By the way, does parity automatically disable it's own autoupdate feature when running via a snap ?

**Comment by elopio** [comment]
As far as I know, it is not doing anything special about autoupdates, which seems to mean that it will try to apply just critical updates. If it tries to update, I guess it will fail because the snap files are read-only. Do you know if an update fails silently, or causes any visible problem?

We could modify the `parity` snap command to always pass `--auto-update none`, but I don't know enough of this functionality to tell if the change is needed, or if it would have other unintended consequences.
