### ISSUE TITLE
UI: Badge fail showing up for the first row

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#7337]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.0-unstable-fcddc7751-20171208/x86_64-macos/rustc1.22.1
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: **no** / yes
> - **Did you try to restart the node?**: no / **yes**

Hi @jacogr :)

The issue is not very simple to reproduce:
- You will need at least 4 accounts (I tested with 10).
- All the accounts should have the same tag. 
- All the accounts should have a given Badge.

Now filter using the tag. 

The result list should show you more than 1 row, each row with 3 results.

The issue is that **in the first row, the Badge never shows up** on the account.
If you click the account to see the details, you will see the badge. If you change the sorting of the list, you will see that it is always the first row that misses the Badge display.

This may be related to #7333 and its recent fix.

**Comment by chevdor** [comment]
As far as I see, you can even see the issue without applying tags and filtering.

**Comment by tomusdrw** [comment]
@jacogr can you have a look?

**Comment by jacogr** [comment]
Ok, this is a _weird_ one, but definately exists,

**Comment by jacogr** [comment]
@chevdor Could you try this branch - https://github.com/paritytech/parity/pull/7454

(Build with `cargo build --release --no-default-features --features ui`)

The reason for asking is that the changed I made (which was actually just cleanups as I went though), made it "just start working". As it stands the issue is weird since the rows have no significance on the display anyway, each indv. card gets handled on it's own.
