### ISSUE TITLE
parity wallet show 0 eth after 20 hours withdraw from bitstamp 

### ISSUE THREAD

**Issue by helxsz** [paritytech/parity#7339]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.4beta (Parity//v1.8.4-beta-c74c8c1-20171211/x86_64-macos/rustc1.22.1)
> - **Which operating system?**: MacOS
> - **How installed?**: via installer binaries 
> - **Are you fully synchronized?**:  (I think it is probably still synchroinzing )
![screen shot 2017-12-19 at 17 18 22](https://user-images.githubusercontent.com/669670/34169857-af93138c-e4e0-11e7-962a-1a2b123b0e08.png)

> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have withdrawaled the eth from bitstamp 20 hours ago, the parity wallet still shows the 0 eth, however I checked the wallet address on the https://etherscan.io/, it already has the transferred eth. 

is it because that not fully synchronized?

**Comment by kirushik** [comment]
@helxsz yes, the yellow icon on your screenshot means that not all bocks have been caught up so far. It turns green when the syncing is done.
Unfortunately, because of #6372, initial synchronization in Parity currently takes longer than expected (especially if you're not on SSD).

Please be patient, your balance in Parity will be updated as soon as block with your withdrawal transaction hits your local node; your funds are safe in the meanwhile (as long as your wallet password and recovery phrase are kept secure).

Please feel free to reopen this bug, if you'll reach "fully synced" state, and the funds would still be not available in your local Parity.

**Comment by 5chdn** [comment]
Duplicate of #7436
