### ISSUE TITLE
Setting up QASH token in parity wallet

### ISSUE THREAD

**Issue by ZNTtrader** [paritytech/parity#7377]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.0
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: yes

I transferred ERC-20 token QASH to my Parity Wallet, but instead of seeing a symbol of the token, I see a question mark (?). Do I need to set up a new token before transferring it to my wallet? How is it done?

**Comment by tomusdrw** [comment]
Parity displays tokens as specified in the Token Registry: https://github.com/paritytech/parity/wiki/Token-Registry
If you are the owner of the TokenReg entry, please update it with an image, otherwise to get rid of question mark it needs to be updated by the entry owner (most likely someone behind the QASH token).

**Comment by ZNTtrader** [comment]
Thank you!

**Comment by 5chdn** [comment]
Please upgrade your client to 1.7.11 or 1.8.5 :)
