### ISSUE TITLE
Parity CLI Options and TOML file config inconsistently use "None", "none", and "null"

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7404]
# INFO
**Which Parity version?**: 1.8.4-beta
**Which operating system?**: MacOS
**How installed?**: homebrew
**Are you fully synchronized?**: N/A
**Did you try to restart the node?**: N/A

# **actual behaviour**

The guidelines for using configuring Parity with either the CLI options or a TOML file config inconsistently use values of values `"None"`, `"none"`, and `"null"`. 

For instance, the default value of CLI Option `--jsonrpc-cors` is shown as being `"None"` at https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options, but the equivalent value when used in the Default config.toml file at https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml it is set as `"null"` instead of `"None"` 
```
[rpc]
cors = "null"
```

Reference: https://github.com/paritytech/parity/wiki/Configuring-Parity

# **expected behavior**

If `"None"`, `"none"`, and `"null"` represent the same value then is there an opportunity to just choose one of them so the documentation is more consistent?

Otherwise if `"None"`, `"none"`, and `"null"` do not represent the same value then is there an opportunity to add a section in the Configuring Parity section of the Parity Wiki that explains the difference between available default values?

# **steps to reproduce**

The values of `"None"`, `"none"`, and `"null"` are used in the Configuring Parity section of the Parity Wiki at https://github.com/paritytech/parity/wiki/Configuring-Parity

**Comment by tomusdrw** [comment]
- `None` indicates that there is no default value for parameter
- `none` indicates that default value for the parameter is `"none"` - a special string that is parsed to have some meaning
- `null` indicates a `null` origin in case of CORS parameters and it's different from `none` (default config file is most likely wrong, since `null` is not a default for that particular parameter).

We are working on making the wiki pages amendable by the community, stay tuned :)
