### ISSUE TITLE
Transaction sended 2 times from account 0xaac92bb57cb3d635bc8e70a4e52e22bf81a925d6

### ISSUE THREAD

**Issue by Sebhabit** [paritytech/parity#7483]
Hi !

I’m running with Parity v1.9.0-20171127 unstable on Linux Ubuntu 64, it was installed from the official binaries. The blockchain was sync and, sure, i restarted the node. The problem was in a transfert between accounts, i have validated the same transaction (password verification) two time to run the transfert. The result was the following : **1 × 2 ethers sended**. It is a security issue, please, maybe **it is better to blank the password field one validation**. So I lost 1 ether.

The first transaction (was wanted (Jan-06-2018 07:39:23 PM +UTC)) :
_0xef1b4affdd83c1e347e95c286cdb443e792cfa69c59a5958ff8c5c31fb452ec8_

The second transaction (was NOT wanted (Jan-06-2018 07:39:23 PM +UTC)) :
_0x40dfe8a5dd486d847547f84f337586b02781fd50acfbb3ab0da7624a3353fda6_ 

Best regards

**Comment by 5chdn** [comment]
Thanks for your report.

First of all, we do not distribute `unstable` builds, only `stable`, `beta`, and `nightly`. It appears you compiled your own version here.

We do not recommend running `unstable` or `nightly` builds because they can contain many bugs that could cause you to lose money. 

In addition, the 1.9 wallet is completely rewritten from scratch and can contain additional bugs.

**Comment by 5chdn** [comment]
Duplicate of #7369
