### ISSUE TITLE
Parity using too much CPU in Ubuntu 16.04

### ISSUE THREAD

**Issue by marcopiraccini** [paritytech/parity#7522]
> I'm running:
>
> - **Which Parity version?**: v1.8.6-beta-2d051e4-20180109 (but the same with older 1.8.x)
> - **Which operating system?**: Linux (Ubuntu 16.04)
> - **How installed?**: `bash <(curl https://get.parity.io -Lk)`
> - **Are you fully synchronized?**: no, few days missing
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

When I run parity the CPU usage is too high, with all my cores running almost at 100%. Then my laptop became quickly unusable and I have to stop parity.
Not sure why: there's a way to limit CPU usage?

**Comment by kirushik** [comment]
@marcopiraccini if it's indeed a CPU issue, you can use system-provided [`nice` utilities](https://askubuntu.com/questions/48708/change-niceness-priority-of-a-running-process) to lower the priority of Parity among other processes.
It might also be the case that actual congestion is caused by I/O work, and then [ionice](https://www.tutorialspoint.com/unix_commands/ionice.htm) will help you to throttle that.

Please keep in mind that on slower machines Parity might have a hard time catching up block-by-block, and throttling here will only make things worse, possibly making your node unable to synch at all.

Feel free to post any additional info/observations about your issue here — I'll then reopen this bug if needed.

**Comment by marcopiraccini** [comment]
Actually, I already used `nice'. Here I launched `nice parity` (no options) and this is the `htop` screen.  
![parity](https://user-images.githubusercontent.com/668050/34893044-d11bbd52-f7db-11e7-832b-38077adeb1c7.png)

I cannot believe I'm the only one...when I launch parity my laptop became pretty unusable...

**Comment by kirushik** [comment]
@marcopiraccini I don't think it's a problem for any program to request up to 100% CPU during a computation-heavy task. And initial syncing of Parity is indeed such task. That's a duty of your OS' scheduler to limit that usage and distribute actual CPU cycles in accordance with user's preferences. If you think you have a counterargument — please correct me.

Therefore, if your OS is unusable when your CPU load is too high — then it's a system-level problem; especially if your CPU consumer is running with niceness 10, so it should give a right of way to any process with high priority.
It might be a misconfiguration of your OS, or some hardware malfunction/overheating leading to unexpected behaviour, or even a bug in the scheduler of kernel you're using.

I will gladly help you to troubleshoot this issue further (I'm also running Ubuntu 16.04 derivative on a laptop, by the way), but so far I see no reason for `parity` to introduce CPU usage throttling directly into the client code.

**Comment by marcopiraccini** [comment]
I'm pretty sure it's not a system level problem: I use this laptop 12h/day and this happens ONLY when I run parity. 
However you are right, the OS should limit the usage. I'll investigate further what happens exactly when the laptop became unusable (actually could be a I/O issue).
