### ISSUE TITLE
No traces available when in dev mode (instantSeal engine)

### ISSUE THREAD

**Issue by 0v1se** [paritytech/parity#7686]
> I'm running:
>
> - **Which Parity version?**: 1.8.6, 1.7.13
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private dev network
> - **Did you try to restart the node?**: yes

I run parity with command: parity --chain chain.json --tracing on --reseal-min-period 0 --unsafe-expose
chain.json is the same as here: https://paritytech.github.io/wiki/Private-development-chain

after mining some blocks I run: curl --data '{"method":"trace_block","params":["0x4"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
and I get: {"jsonrpc":"2.0","result":[],"id":1}

Block number 4 is imported. I have one transaction in it.
When I use ropsten/mainnet everything's working fine - I get traces I need.

If I request transaction trace I get null:
curl --data '{"method":"trace_transaction","params":["0x08e6d9ba3f00e31320b960173a29f1d5925d401c4943ebc171eca6b38189cdd9"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":null,"id":1}

**Comment by tomusdrw** [comment]
Indeed self-mined blocks does not contain traces and are shortcuted to the chain so the traces are never produced. We should probably ditch short-cutting in case traces are enabled.

Affects not only dev chain, but will also be broken on all engines.

**Comment by ascjones** [comment]
I was able to reproduce this as described with 1.8.6, as well as the latest stable release 1.8.10.

However, in the most recent beta [1.9.4](https://github.com/paritytech/parity/releases/tag/v1.9.4) the trace requests work as expected. Haven't been able to figure out exactly which commit has fixed it (#7979 is a tracing fix but the prior release 1.9.3 also worked okay).

@0v1se are you able to run the latest beta release? If so give it a try and see whether the issue is fixed.

Note that the chain.json specified [here](https://wiki.parity.io/Private-development-chain) is now out of date compared to the config used when running 1.9.4 with `--config dev`. See https://github.com/paritytech/parity/blob/master/ethcore/res/instant_seal.json which has enabled the byzantium features and the registrar account.

**Comment by 0v1se** [comment]
I tried https://github.com/paritytech/parity/releases/tag/v1.9.4 and confirm issue is resolved in latest beta.
Will use it for development.
Thank

**Comment by andrewtoth** [comment]
I'm running v2.5.5 and there are no traces available.
