### ISSUE TITLE
investigate if thread::sleep is really needed in hw module

### ISSUE THREAD

**Issue by debris** [paritytech/parity#7793]
it may potentially fix: #7516

suspicious code snippets:

https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/hw/src/lib.rs#L146-L158

https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/hw/src/lib.rs#L190-L204

https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/hw/src/ledger.rs#L239-L245

https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/hw/src/trezor.rs#L206-L212

and check out these changes:
https://github.com/dcuddeback/libusb-rs/compare/master...paritytech:master

**Comment by debris** [comment]
cc @niklasad1

**Comment by niklasad1** [comment]
@debris 
I think you can close this issue but just the clarify why the delay is necessary (but these are moved into separate threads now and should not block ```the main thread```)

1. At least Trezor need some time boot-up ~250 ms 
2. The loop iterations are unnecessary if a long enough delay is introduced
3. There are two cases:
    * The device is connected when parity starts (the delay could probably be skipped but that seems a little bit risky because we don't know how long the device have been connected)
    * A device connects/disconnects when parity is running

All this should be fixed in [#7860](https://github.com/paritytech/parity/pull/7860) but it is at least ```investigated```
