### ISSUE TITLE
ERC20 token not displayed in UI

### ISSUE THREAD

**Issue by jimgwies** [paritytech/parity#7907]
I purchased a new token called KRIOS which is an  ERC20 token, and had the tokens sent to my parity address, and after several weeks it has never showed up. Do I need to configure my parity wallet differently since it is a token rather than an ether coin? 

_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by Aggour** [comment]
This is probably due to your node not being synchronized.

Please provide the info so we can better identify the cause:

_Which Parity version?: 0.0.0
Which operating system?: Windows / MacOS / Linux
How installed?: via installer / homebrew / binaries / from source
Are you fully synchronized?: no / yes
Which network are you connected to?: ethereum / ropsten / kovan / ...
Did you try to restart the node?: no / yes_
