### ISSUE TITLE
Can you just delete the wiki on GitHub? Or provide better redirect links?

### ISSUE THREAD

**Issue by hakusaro** [paritytech/parity#7935]
This is more of a project management request. For the last two weeks, I've been googling questions for parity. Standard research stuff. Unfortunately, my Google search results always turn up links to the GitHub wiki, which has been marked as out of date and "archived," but not the new wiki. This is probably because Google doesn't index a page if it's identical to an existing page. It treats those as duplicates and doesn't show them.

Here's a sample Google search result:

![screen shot 2018-02-18 at 10 45 15](https://user-images.githubusercontent.com/532647/36354945-0660052a-1499-11e8-926e-3eb60a9d8cde.png)

Since the new wiki has all of the content from the old wiki, you're just shooting yourself in the foot on search engines. Worse, each page doesn't provide the link to the new canonical page -- it just says to refer to the new wiki. This means that any person who landed at the wiki from a search engine now has to search the new wiki for the same page.

I propose any of the following:

1. Delete the GitHub wiki, since it's just taking up Google storage space. That is, turn the wiki feature off in GitHub.
2. If you care about the contents, create a repository and upload the wiki there. There's a chance that Google will index it, though, and that creates the same problem again.
3. If you don't want to take option 1 or 2, at least update each GitHub wiki page with a direct link to the equivalent page on the new wiki.
4. Delete the actual contents of every wiki page, then replace the contents with a direct link to the new page. This helps solve stagnant links on the normal internet.

I'm a new ethereum user, and I keep finding this whole problem quite frustrating. Broken links pointing to the old wiki and landing there are becoming more and more of an annoyance as I need to refer to more pages faster. It also doesn't help when many questions on the Ethereum stack exchange point to old wiki articles, which now have an "abandoned" header and those have to be manually changed. I'm more technically savvy than most and even I find this absolutely hair splitting.

**Comment by gituser** [comment]
the actual docs are here I believe - https://paritytech.github.io/wiki/JSONRPC-eth-module

wiki can be just redirected there

**Comment by 5chdn** [comment]
I'm not sure if markdown allows redirects, does it?

**Comment by roninkaizen** [comment]
unfortunately not- really sorry about it- some are really right, some are not-

due to the change to 1.9 some of the documentation also needs fresh "passport-pictures"-
there were changes, which irritated some of the users- comparing documentation to "live-view"-

let us do that combined, based on the old wiki, there were several changes,
which are also about to be logically integrated-
which could be declared, why and how- by devs.

i oppose setting up certain controlled google-space for that- no splitting up information from software source brought more help for users and node-owners.
i propose a decentralized, community driven manual, incentivized even from me if needed- (to get actual qualified articles)  as 5 users checked the manual and came to successful solutions with the choosen document the writer of that certain articles could be honored more than today.
we need stronger improvement at this point-
and BIG WARNINGS for CONTRACT DESIGNERS TO USE ONE OF THE TESTNETS-
don't we?

**Comment by 5chdn** [comment]
Done
