### ISSUE TITLE
Error on parity start: OPENSSL_1.0.2 not found (required by parity)

### ISSUE THREAD

**Issue by travs** [paritytech/parity#8009]
> I'm running:
>
> - **Which Parity version?**: 1.9.3-beta and 1.8.10-stable
> - **Which operating system?**:  Ubuntu Linux
> - **How installed?**: via binary (oneline installer: get.parity.io)
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: none
> - **Did you try to restart the node?**: cannot

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

In Travis CI we are running into an issue when trying to start a parity instance.

The install step passes, but when trying to run `parity` we get an error like this one:

```
$parity --chain ./utils/chain/chainGenesis.json --jsonrpc-apis all
parity: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by parity)
parity: /lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by parity)
```

**Comment by 5chdn** [comment]
Thanks for reporting.

Which ubuntu Version is that? Do you have libssl-dev installed?

Do we properly check for dependencies @ddorgan @fevo1971 - could you check that?

**Comment by travs** [comment]
@5chdn 
Yes I install libssl-dev by doing `sudo apt-get install openssl libssl-dev libudev-dev` right before installing parity.

Ubuntu version is Trusty (14.04).

**Comment by unixfox** [comment]
Same issue with Debian Jessie (8).

Ubuntu 14.04, Debian 7 & 8 use openssl 1.0.1 instead of openssl 1.0.2:
- https://packages.ubuntu.com/trusty/openssl
- https://packages.debian.org/jessie/openssl
- https://packages.debian.org/wheezy/openssl

**Comment by ddorgan** [comment]
We could rebuild these using 1.0.1 maybe ... but this is no longer in support and has multiple security issues. Will review some options.

**Comment by ddorgan** [comment]
@travs Could you maybe try the snap package instead? This seems to work much better on older distros from my testing. Thanks for the input @General-Beck 

Just run:
``` 
sudo apt-get install snapd 
sudo reboot
```
Then run:
```
sudo snap install parity
```
Let us know if this helps.

**Comment by ddorgan** [comment]
@travs do you have any update on this?

**Comment by unixfox** [comment]
@ddorgan Snap is not the solution because:
- it requires root access
- it recreates a directory of the blockchain for each updates and this takes quite lot's of space after multiple updates, it has been discussed here: https://github.com/paritytech/parity/issues/7254

Nowadays launching parity on Debian 7/8 & Ubuntu 14.04/16.04 without root requires compiling it from source, it's quite a pain because of the dependencies. I got a success full build with [Linuxbrew](http://linuxbrew.sh/) using [this formula](https://gist.github.com/unixfox/314848fcab6373cdea1ffacb01478298) but it was not easy.

Why you can't provide a binary for olders OS with openssl 1.0.1?

**Comment by kirushik** [comment]
We're going to completely drop the openssl dependency as a part of #7829, building a (hopefully) distro-independent linux binary.

I'm closing this issue (since it's superceeded), but please feel freee to use this thread to continue the discussion on problems with snapcraft and possible alternatives.
