### ISSUE TITLE
Slow archive sync

### ISSUE THREAD

**Issue by k06a** [paritytech/parity#8112]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.11
> - **Which operating system?**: MacOS (Mac Book Pro 15" 2017)
> - **How installed?**: homebrew
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: yes

I am using following options:
- `--pruning archive`
- `--cache-size 4096`
- `--mode active`
- `--db-compaction ssd`

First 2.2M blocks were synced at speed about 60Mgas/s, but then I stopped process and then continued and speed now is about 0-1Mgas/s and sometimes it is about 40Mgas/s. The most of time speed is 0-1Mgas/s, about 90%.
![photo_2018-03-14_11-55-15](https://user-images.githubusercontent.com/702124/37392216-9460ee46-277e-11e8-885c-9fc29f4d3674.jpg)

I also can see a lot of [hidden space](https://daisydiskapp.com/manual/4/en/Topics/HiddenSpace.html?subtopic=StillHiddenSpace) on my SSD it is always growing and sometimes pruning to zero:
![photo_2018-03-14_11-56-13](https://user-images.githubusercontent.com/702124/37392262-b5a44e22-277e-11e8-9bba-8d49bad78524.jpg)

**Comment by k06a** [comment]
<img width="1243" alt="2018-03-14 12 50 41" src="https://user-images.githubusercontent.com/702124/37395080-5f5c4bfc-2786-11e8-8dbd-f57b99adc0c3.png">

**Comment by k06a** [comment]
Didn't know what just happened:
<img width="1250" alt="2018-03-14 12 53 57" src="https://user-images.githubusercontent.com/702124/37395244-d72c17f2-2786-11e8-9bbd-92f805704f24.png">

**Comment by k06a** [comment]
For some reason it downloaded more than 2.4M blocks and I noticed `--networkid 3` not gives me ropsten, added `--chain ropsten` and restarted with empty DB.

Is it possible to have two configs in one? For mainnet to be `light` and for ropsten to be `archive`.

**Comment by k06a** [comment]
I like current speed, not going to stop it.
<img width="1254" alt="2018-03-14 13 32 16" src="https://user-images.githubusercontent.com/702124/37397250-2b9656ae-278c-11e8-8b12-00b92ff04b42.png">

**Comment by Tbaut** [comment]
@k06a the network was attacked during these blocks and it is therefore expected to have a slower sync since the blocks have a great amount of transactions. See [our documentation](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#sync-is-stuck-around-block-2421000-or-2675000)

Network ID 3 is Ropsten but the flags `--network-id` and `--networkid` override the network id, it does not select the chain to sync (you found it, the right flag is `--chain`)

It is definitely possible to have 2 config files, just load the one you need using `-c your-file.toml`

For quicker feedback, feel free to ask anything in the [gitter chat](https://gitter.im/paritytech/parity)
