### ISSUE TITLE
"multiple applicable items in scope" & "multiple `flatten` found" (while compiling from source)

### ISSUE THREAD

**Issue by xftroxgpx** [paritytech/parity#8211]
> I'm running:
>
> - **Which Parity version?**: 

commit 8c02211dc369f109d64701838ea2b57ddc2e3a11 (HEAD -> master, tag: nightly, origin/master, origin/HEAD)

> - **Which operating system?**:  

Linux
> - **How installed?**: 

not yet, compiling from source...

**steps to reproduce**

1. git clone https://github.com/paritytech/parity
2. cd parity
3. cargo build --release

```rust
error[E0034]: multiple applicable items in scope
  --> /home/xftroxgpx/build/2nonpkgs/rust.stuff/parity/ethstore/src/accounts_dir/memory.rs:33:45
   |
33 |         Ok(self.accounts.read().values().cloned().flatten().collect())
   |                                                   ^^^^^^^ multiple `flatten` found
   |
   = note: candidate #1 is defined in an impl of the trait `std::iter::Iterator` for the type `std::iter::Cloned<_>`
   = note: candidate #2 is defined in an impl of the trait `itertools::Itertools` for the type `_`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0034`.
error: Could not compile `ethstore`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

```
rustc 1.26.0-dev (4be5d360c 2018-03-23)
binary: rustc
commit-hash: 4be5d360cd8a9338d1408b3998874313240db395
commit-date: 2018-03-23
host: x86_64-unknown-linux-gnu
release: 1.26.0-dev
LLVM version: 6.0

cargo 1.26.0-dev (bcd0300f 2018-03-23)
release: 1.26.0
commit-hash: bcd0300f0e2b572e81fa17e88dcb927aa95d6b4e
commit-date: 2018-03-23
```

**Comment by niklasad1** [comment]
Yeah, but officially `parity` is on the stable channel of Rust as the `rust-toolchain` file specifies where those warnings doesn't show yet at least!

**Comment by kirushik** [comment]
I don't think rust-lang/rust#48213 is going to land in stable Rust anytime soon, so I'm lowering the priority.
Also, I don't see any reason to run on `nightly`, even in development — since both incremental compilation and RLS are available in `stable`.

**Comment by 5chdn** [comment]
I'm even further lowering the priority by closing this issue so we can take care once this actually is an issue :)

**Comment by eosclassicteam** [comment]
@5chdn Right now default Rust version is 1.29.0 and I am getting this error with default rust compiler 😂 Please reopen this issue.

**Comment by vincell1** [comment]
I am also facing same issue with default rust compile.

  Compiling ethstore v0.2.0 (http://github.com/paritytech/parity?rev=991f0ca#991f0cac)
error[E0034]: multiple applicable items in scope
  --> /Users/sandeepkumar/.cargo/git/checkouts/parity-dc9825eb65b3adf1/991f0ca/ethstore/src/accounts_dir/memory.rs:33:45
   |
33 |         Ok(self.accounts.read().values().cloned().flatten().collect())
   |                                                   ^^^^^^^ multiple `flatten` found
   |
   = note: candidate #1 is defined in an impl of the trait `std::iter::Iterator` for the type `std::iter::Cloned<_>`
   = note: candidate #2 is defined in an impl of the trait `itertools::Itertools` for the type `_`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0034`.
error: Could not compile `ethstore`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [target/release/bridge] Error 101

**Comment by niklasad1** [comment]
@eosclassicteam @sandakersmann 

You must be compiling an old version of `parity` this was fixed for a long time ago, see https://github.com/paritytech/parity-ethereum/commit/981554cf74980c9470abf23039ad39e75246eef8#diff-47124c46f87ec7a3ff6ceb7561c573a7

**Comment by niklasad1** [comment]
@sierra-golf 

That version is not supported by `rust 1.30.0` you need to downgrade to `1.29.1` or earlier and it should work fine

**Comment by sierra-golf** [comment]
@niklasad1 thank you for clarifying that. I might add that in `old-stable-*` branches `rust-toolchain` file points to `stable` which is a bit misleading now.
