### ISSUE TITLE
util/patricia_tree `eliminate expect()`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity#8222]
https://github.com/paritytech/parity/blob/master/util/patricia_trie/src/lookup.rs#L58

**Comment by ascjones** [comment]
I added this as part of #8033. Originally the call to Node::decoded was unsafe for invalid rlp, because of the unwraps in Rlp e.g. https://github.com/paritytech/parity/blob/master/util/rlp/src/rlpin.rs#L126

The DecoderErrors are now propogated and can be handled further up. In this case I originally added a DecoderError case to `TrieError` but ran into a couple of issues and decided to add the expect for expediency, reasoning that it behaves at worst as badly as before.

Now the wider changes are nearly done I can look at this again (or someone else). IIRC the slight issues I had were about the data to store in the DecoderError case since it is not Clonable, and the H256 key is not always available in the context. So should be simple once this is figured out.
