### ISSUE TITLE
Double Sends

### ISSUE THREAD

**Issue by candro** [paritytech/parity#8247]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.11
> - **Which operating system?**: Windows Server 2012
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

We use Windows Server, where "Parity" is installed. The program instance is launched from the user1 and the tab in the browser is opened, and the wallet tab is opened on user2.
If we send money from the user2 browser, then we can create 2-3 transactions.

**Comment by 5chdn** [comment]
> If we send money from the user2 browser, then we can create 2-3 transactions.

And how?

**Comment by 5chdn** [comment]
Also please upgrade your node.

**Comment by candro** [comment]
Just people should know about this bug. I'll check in the latest stable version.

**Comment by 5chdn** [comment]
You did not describe the bug yet. Are you signing the transaction twice or the signed transaction broadcasted twice? In neither of the two options it would be a bug, so please expand what you mean by "double sends".

**Comment by villesundell** [comment]
I think I have a variation of the same problem: I accidentally participated twice to EOS crowdsale, instead of only one transaction I planned originally to do :laughing: For me the damage is not huge (both were 1 ETH each), but the problem is real.

It is possible that I accidentally pressed the confirmation button on the signer twice, but because both of the transactions had different nonce, both of them passed as a separate transaction.

Should nonce be decided already when coming to the Signer? If the nonce would have been the same, this would not have happened.

(Parity v1.9.3-20180219 beta, account here: https://etherscan.io/address/0x41B2326e02c2075eab850837aa5F06234A81E9b9 )
