### ISSUE TITLE
parity1.9.5

### ISSUE THREAD

**Issue by ttt2008** [paritytech/parity#8332]
wrap  store  keep on 63.64%，in win10

**Comment by Tbaut** [comment]
Can you please answer the questions :

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

and eventually [run parity with command line](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-windows-) and post here its output.
