### ISSUE TITLE
Info: data compression on disk

### ISSUE THREAD

**Issue by wnz99** [paritytech/parity#8353]
Hi,

I am running a few Parity instances on a zfs filesystem with deduplication on, for testing purposes.

Having no info how Parity stores and organized data in the db folder, my initial expectation was that the content would have been quite similar between the instances given that the clients are syncing to the same network.

Unfortunately, the dedup ratio is very close to 1.1x. This leads me to thinking that files are somehow compressed. Therefore blocks are not equal and dedup is useless in such scenario.

I have also played a little bit with zfs clones by assigning a clone of a full sync to each Parity instance and it appears that the clones quickly diverge from the original copy.

Could you please provide some more insight on this? Is there any strategy/config which can provide data stored in a way that can be efficiently deduped?

**Comment by folsen** [comment]
Parity uses RocksDB under the hood, which has its own compaction algorithms, so indeed the data is being compressed to some degree. Work is being done to replace RocksDB in some places, but it's not in the Soon™ horizon really, when we get there dedup might be more effective because it uses a more deterministic storage strategy. Closing this issue until then. (See https://github.com/paritytech/paritydb)
