### ISSUE TITLE
 restore my account from the 12 words mnemonic phrase, but get new account with new address.

### ISSUE THREAD

**Issue by neocarmack** [paritytech/parity#8548]
_Before filing a new issue, please **provide the following information**._

 I'm running:

 **Which Parity version?**: 1.10.0
 **Which operating system?**:Linux，Ubuntu
 **How installed?**: via installer 
 **Are you fully synchronized?**: no， not yet
 **Which network are you connected to?**: ethereum 
 **Did you try to restart the node?**: yes，many times

I‘m trying to restore my account from the 12 words mnemonic phrase via the Parity-ui. But after i submitted the 12 words, i get a new account with a new address starting with 0X00......., which is not the one corresponding the mnemonic words i input.

It took me many days to sync, but parity looks dead, blocks count stops at 1,015,XXX. Am i wrong about sth?

**Comment by Tbaut** [comment]
> i get a new account with a new address starting with 0X00

Then the mnemonic you entered is not the one given originally. You should double check, make sure  the spelling is good, white space, the words [here is the supported list](https://raw.githubusercontent.com/paritytech/wordlist/master/res/wordlist.txt)

>It took me many days to sync, but parity looks dead, blocks count stops at 1,015,XXX

You are not synced as the top of the chain is currently around 5.xM blocks. I believe that the warp sync failed. Here is what I advise you to do:

Syncing is with warp is tricky these days because of [several issues we're working on](https://wiki.parity.io/Known-Issues-Priorities), here is my rule of thumb :
1. delete your database using `parity db kill`
1. start parity again with the flag `--warp-barrier` following [these instructions}(https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#why-is-warp-synchronization-so-fast)
1. if the nodes starts downloading snapshots, you're good, let it do the warp sync. If the node starts syncing showing block numbers (and not the snapshots) it means failed to warp sync.
1. stop parity and start it again -> jump back to 2.
1. if after 4-5 attempts you never get the warp sync.. then stop the process, grab a coffee and try later
1. if all you need is playing with the wallet, consider using the light node using `--light` flag. This doesn't use snapshots and only sync block headers. It's secure and quick.

This is not per se a parity problem, just some challenges brought by the growing network, it's a good thing :)

**Comment by neocarmack** [comment]
@Tbaut thanks, i will try again
