### ISSUE TITLE
Move tests into their own modules

### ISSUE THREAD

**Issue by peterjoel** [paritytech/parity#856]
It will make it easier to add tests and reusable test fixtures if they are moved into their own modules. These modules could be in separate files or in the same file as the source code.

@gavofyork 
@arkpar 
@NikVolf

**Comment by NikVolf** [comment]
can you provide an example how that will be helpful exactly?

**Comment by peterjoel** [comment]
A separate module for tests is idiomatic Rust. It doesn't have to be different file.

In the case of parity, one example might be some contracts and transactions that are re-usable across many tests. It's much easier to manage those if the tests are in their own module. My preference is for separate files, but I can see the appeal of putting them in the same file if they are short tests.

**Comment by gavofyork** [comment]
prefer same file (locality rules) unless there is a mitigating circumstance, but otherwise up for it.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days it is realistic to refactor the tests _some day maybe_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by debris** [comment]
imo this issue is too general. It applies to all tests within all parity's libraries. If we want to make it realistic, it should be more specific eg. 'move all integration** tests from parity/ethash into their own modules'. 

** *Integration tests should be moved to test directories, but all unit tests should remain where they are.*
