### ISSUE TITLE
Add "multi" option in spec.json for BlockReward contract

### ISSUE THREAD

**Issue by varasev** [paritytech/parity#8704]
Parity 1.11.1 doesn't have "multi" option in `spec.json` for `BlockReward` contract. Therefore, once the `BlockReward` has been deployed, it cannot be changed.

The suggestion is to add the same "multi" option as it's done for validator set: https://wiki.parity.io/Validator-Set.html#multi-set

**Comment by rphmeier** [comment]
I would lean away from adding too many "Multi" parameters, so we should consider this carefully before implementing. As a workaround for now you can write an upgradeable proxy contract for the block reward logic.

**Comment by andresilva** [comment]
Agreed, "multi" makes sense for validator set because there are different types of interfaces (static list, contract, safe contract). As @rphmeier suggested you should deploy an upgradeable proxy contract, this also has the advantage that you'll be able to update the block reward contract without an HF.
