### ISSUE TITLE
unable to connect to a node, db corrupted error

### ISSUE THREAD

**Issue by toodlesmcgee** [paritytech/parity#8716]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.1
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no 

Non technical person here, i downloaded version 1.11.1, UI, and Parity Ethereum chrome extension (stating not connected to a local node http://127.0.0.1:8180)  to access my wallet. When i launch version 1.11.1 its stating db corrupted and column families not opened  co15, co10, co13, co16, co11 then states attempting repair and the CLI box disappears. My clock is synchronized. I just need access to my wallet again to send some tokens.

**Comment by Tbaut** [comment]
Hey @toodlesmcgee, you seem to have several issues that are not related with each other.

Regarding the DB corruption, it is a duplicate from #7748
This error indicates a DB corruption most likely due to a memory error. Could you please make sure that your memory passes a memtest?
You will need to do a `parity db kill` and resync the whole blockchain (tipp, [use --warp-barrier](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#why-is-warp-synchronization-so-fast))

Concerning the UI, as written in [our wiki](https://wiki.parity.io/Parity-Wallet): The user interface previously accessible from the browser in versions <=1.9 is now released as a standalone app. This is why you can't connect to http://127.0.0.1:8180.

If you have some more question, feel free to jump into a chat on our [Gitter channel](https://gitter.im/paritytech/parity).
