### ISSUE TITLE
Parity Sync Freezes midway!

### ISSUE THREAD

**Issue by rasarasan** [paritytech/parity#8729]
I'm running:

 **Which Parity version?**: Parity v1.11.1-20180515 beta
 **Which operating system?**:  MacOS 
 **How installed?**: via installer
 **Are you fully synchronized?**: no
 **Which network are you connected to?**: ethereum 
 **Did you try to restart the node?**:  yes

I have my storj tokens in my parity wallet. But it has been syncing for days/weeks now. After a while it freezes with no progress or end in sight :( Please see the attached screenshot. Will appreciate a quick response as I have spent too much on time on this already !

![parity-sync-issue](https://user-images.githubusercontent.com/45295/40673128-da69e23e-633e-11e8-9d1f-ed52bfa787c1.jpeg)

**Comment by Tbaut** [comment]
I'm sorry to hear you're having problems getting in sync. Syncing with warp is tricky these days because of [several issues we're working on](https://wiki.parity.io/Known-Issues-Priorities). To give us the best chances to succeed, you should learn [how to launch parity with the command line](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-mac-osx). Here are my rules of thumb :
1. make sure parity UI is shut down an no parity process is running.
1. delete your database using `parity db kill` (in the terminal)
1. start parity again with the flag `parity --warp-barrier 5680000`
1. if the node starts downloading snapshots, you're good, let it do the warp sync. If the node starts syncing showing block numbers (and not the snapshots) it means failed to warp sync.
1. stop parity and start it again -> jump back to 2.
1. if after 4-5 attempts you never get the warp sync.. then stop the process, grab a coffee and try later

Here is an extensive explanation of what the command line output means: https://wiki.parity.io/FAQ-CLI,-Mining,-and-Networks.html#what-does-paritys-command-line-output-mean
This is not per se a parity problem, just some challenges brought by the growing network, it's a good thing :)

**Comment by Tbaut** [comment]
Yes, this looks good. Just need to wait for the warp sync to end and the latest blocks to sync. Depending on your connection it can take ~3h overall.

**Comment by Tbaut** [comment]
We've found some issues in the v1.11.1 related to the sync (https://github.com/paritytech/parity/pull/8710 https://github.com/paritytech/parity/pull/8544 https://github.com/paritytech/parity/pull/8658) that will be resolved in the next minor release (should come this week.) From this point, warp sync should be more reliable.

**Comment by rasarasan** [comment]
My node is almost synced and I am able to see my tokens now. When I try to transfer I get this error now.  :(
![paritysenderror](https://user-images.githubusercontent.com/45295/40992264-52120278-68c4-11e8-9b0c-112795a0c5ff.jpeg)

**Comment by Tbaut** [comment]
This is not a related issue @rasarasan. Please open a new one (in https://github.com/Parity-JS/shell/issues if related to the UI).
