### ISSUE TITLE
Question about pending transaction queue

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity#8740]
Greetings!
Is there any way to find out which pending transactions is no more in the queue? In few hours I receive about 30'000 pending TX with `eth_getFilterChanges` on `eth_newPendingTransactionFilter` filter which are not even in block and not anymore in the queue.. they simple varnishes.
I can use `eth_getTransactionByHash` for check pending TX, but this is huge performance loss.

I use `Parity/v1.10.4-stable-39b9f1e25-20180514/x86_64-linux-gnu/rustc1.25.0` with `--tx-queue-mem-limit=1024 --tx-queue-size=128000` flags.

**Comment by Tbaut** [comment]
Your node listens to the network and will potentially receive a lot of transactions. As explained in your previous issue (https://github.com/paritytech/parity/issues/8694), the queue can be configured. Now because of your configuration, you may not accept them all in your queue. Some will inevitably get dropped and this is expected.

May I ask you what you want to do with these transactions?

**Comment by iFA88** [comment]
> May I ask you what you want to do with these transactions?

Answered to the same question here: #8741

Can you please tell me which conditions are for dropping pending transaction? Like:
- Queue length limit
- Queue memory limit
- Minimum gas price flag (`--min-gas-price`).
In this situation I receive the transaction which below the min-gas-price in the filter?
- Processed in block

**Comment by Tbaut** [comment]
I've started to write a doc about this, please find it here: https://github.com/paritytech/wiki/blob/Tbaut-tx-queue-doc/Transactions-queue.md

**Comment by iFA88** [comment]
Great!
