### ISSUE TITLE
Parity token registry hangs-on forever with everything filled in and "register" never becomes active

### ISSUE THREAD

**Issue by WonkyGiraffe** [paritytech/parity#8773]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity v1.11.1-20180515 beta
> - **Which operating system?**:  Linux
> - **How installed?**: .deb
> - **Are you fully synchronized?**:yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:yes

I have all the fields in Token Registry Dapp filled in correctly. 
The one with the contract address keeps the circle "circling" forever and thus the "Register" button never becomes active.
Node was fully synced and I waited for hours.

**Comment by Tbaut** [comment]
Parity UI has been separated from the node and it now has its own repository: https://github.com/Parity-JS/shell/issues to be managed and maintained by the community. Please report your issue here.

It is advised to get your token listed here as we will push a more general knowledge base in teh future. https://github.com/ethereum-lists/tokens
