### ISSUE TITLE
Parity service running in background, but not launching in browser

### ISSUE THREAD

**Issue by fidaaayoub** [paritytech/parity#8836]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.3
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: not sure
> - **Which network are you connected to?**:not sure
> - **Did you try to restart the node?**: i turned whole laptop off and on, and i tried to install the newer version even. 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

when i click on parity from Launchpad, it appears for few seconds and then disappear.

when i catch it and click open parity... no action happens.
if i go directly to browser and put the IP address of my node. it gives an error that it's not able to establish connection. in the meantime, if i check my laptop Activity Monitoring, i  can see parity service running and consuming significant amount of resources

**Comment by Tbaut** [comment]
From your description, I am not sure if there is an actual problem or if this is expected, here is why.
As you can read [here](https://wiki.parity.io/Parity-Wallet) the user interface from the browser is not available anymore, it's therefore normal to not see it. Please have a look at the link above to learn how to see the User Interface in Parity UI, a dedicated app.

Once you installed it and launched it, if you see the interface, then all good, if not: regarding the fact that nothing happens when you launch parity. It could be a problem with the database that got corrupted. To understand the root cause, please [launch parity with the command line](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-mac-osx) and visit our [Gitter chat](https://gitter.im/paritytech/parity) to get help about the error that you see.
