### ISSUE TITLE
Support consensus engines without a single proposer.

### ISSUE THREAD

**Issue by afck** [paritytech/parity#8888]
We would like to implement a consensus engine based on [Honey Badger](https://eprint.iacr.org/2016/199.pdf) for the POA Network, and we are wondering whether:

* you would be open to merging it into master once it is functional,
* the current `Engine` trait is suitable for this kind of algorithm, and if not,
* you would be open to merging some refactorings to make Parity support it.

In Honey Badger, in each round/epoch, _every_ node proposes a subset of transactions from its mempool, and the algorithm reaches agreement on a union of some of those subsets. The main differences compared to the existing `Engine` implementations are:

* There is no single block proposer. Instead, every node _learns_ about the next agreed batch, which may contain the transactions proposed by the node itself, as well as transactions the node doesn't even have in its mempool.
* The engine will need to deterministically produce a new block from the batch: process all of its valid transactions and sign the result. This means that some of the `Miner`/`TransactionQueue`/`transaction-pool` functionality — prioritizing transactions and picking the ones to propose — needs to happen _before_ each consensus round, while other `Miner` functionality — producing a new block and processing the transactions — needs to happen _after_ the consensus round has produced an output.
* For performance, Honey Badger relies on low-latency, high-bandwidth targeted validator-to-validator messages, so the validators will probably need to establish a separate set of connections to each other.
* We would introduce our general [Honey Badger implementation](https://github.com/poanetwork/hbbft) as a dependency.

**Comment by rphmeier** [comment]
I'm familiar with honeybadgerBFT and similar consensus algorithms, and this was a part of the motivation for the `Engine`/`Machine` split in the architecture of Parity, where engines define exactly what properties of the state machine they need for their operation.

Although there is no actual "proposer" for HoneyBadgerBFT, there are a couple things to consider:

The EVM requires an `author` value to be accessible. The EthereumMachine provided by Parity operates only on blocks which contain an author field. Refactoring Parity to use blocks without an author field would be a significant chunk of work. I'd recommend just having your block validity function require that `author` be zeroed or something (since this is almost equally efficient as not having it at all w/ RLP encoding)

HoneyBadgerBFT as described in the paper allows nodes participating in the consensus to come to an agreement, but proving that agreement has been reached to non-consensus nodes requires some form of justification. This is the "seal" type in the `EthereumMachine`'s block type. There are a few options for generating this seal:
  - provide an entire transcript of messages in the view of a single replica, which proves all common coin instances and threshold decryption shares. this is infeasible space-wise
  - provide a list of any 2f + 1 signatures on the block header, adding an extra step to HBBFT to multicast these signatures
  - provide a 2f + 1 threshold signature on the block header, adding an extra step to HBBFT to multicast the signature shares

Note that the first two options can lead to different valid seals being created (even if no authorities are byzantine), which would require significant refactoring in Parity to ensure that the blockchain is based on the "bare" hash of the header and not the hash with the seal included.

**Comment by rphmeier** [comment]
Also: I think these kinds of internal-communication-heavy consensus play really nicely with the `futures` model. 

This feature would be orthogonal with #8664 which intends to make block production an asynchronous process within the engine, providing only a stream of network messages and a sink for output messages.

**Comment by afck** [comment]
Thanks, but don't congratulate us too early: `hbbft` isn't _quite_ done yet. (Encryption of the proposed transactions is still missing; common coin is under way.)

Yes, we were thinking of using 2f + 1 (or just f + 1?) signatures as the seal (in an extra message round, which could happen in parallel with the Honey Badger epoch for the _next_ block, I guess), but a threshold signature would make more sense: and Honey Badger uses threshold signatures anyway, so we should have the necessary tools available.

> a stream of network messages and a sink for output messages

Could these even be targeted, or broadcast-only? Or should we use separate direct connections anyway if we need low-latency and high-bandwith channels?

**Comment by afck** [comment]
You're right, maybe 2f + 1 is safer. Honey Badger requires that many honest nodes anyway, so if we fail to collect that many signatures it's better to stop immediately rather than accept a block singned by fewer than that.

> all authorities (defined by engine), which is the network requirement for HoneyBadger AFAIK

Most messages are broadcast, but not all: Crucially, the biggest ones are targeted, i.e. sent from a validator to a single other validator. Honey Badger only achieves a high throughput and low latency if that kind of communication is high-bandwidth (broadcasting all of them would waste a lot of bandwidth) and low-latency (if they are routed via several hops, the block rate would be much lower), so I still think it might be necessary to create a separate set of direct connections.
