### ISSUE TITLE
parity_removeTransaction does not work

### ISSUE THREAD

**Issue by candro** [paritytech/parity#9007]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.3-stable-b9ceda3-20180507/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

**Procedure:**

1. personal_signTransaction(txData, pwd);
2. eth_sendRawTransaction(rawTransaction);

Suppose that after the call to sendRawTransaction some error has returned. Money was not enough on this wallet. I can send money from another wallet, on which there is just enough money. But I have to delete the local transaction, otherwise, when the necessary amount appears on it, the money will go by itself.

**What I want should do:**

1. parity_removeTransaction(txHash);
2. parity_localTransactions(); //-- Check whether the transaction was deleted

But the transaction is not deleted, in the response the result is null. BUT, if I restart parity, it will disappear. What is the problem?

**Comment by candro** [comment]
Transaction status - "rejected"

**Comment by Tbaut** [comment]
Please upgrade your node to the latest release: https://github.com/paritytech/parity/releases

To override a transaction, you should send another valid transaction with the same nonce (you can also make sure the gasPrice is also higher so that it gets prioritized). 

The other way to do is to restart your node with `--no-persistent-txqueue`
